# Rego test for Elasticsearch with VPC
# Validating rule elasticsearch_vpc: Deny if elasticsearch resource does not contain a vpc

package rules.elasticsearch_VPC

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

test_elasticsearch_VPC {
	pol := policy with input as mock_input
	resources := {p.id: p.valid | pol[p]}

	resources["aws_elasticsearch_domain.invalid-es"] == false
	resources["aws_elasticsearch_domain.valid-es"] == true
}

# Mock input is generated plan for elasticsearch_vpc.tf
mock_plan_input = {
	"format_version": "0.1",
	"terraform_version": "0.12.28",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "aws_elasticsearch_domain.invalid-es",
			"mode": "managed",
			"type": "aws_elasticsearch_domain",
			"name": "invalid-es",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"cluster_config": [{
					"dedicated_master_count": null,
					"dedicated_master_enabled": false,
					"dedicated_master_type": null,
					"instance_count": 1,
					"instance_type": "m4.large.elasticsearch",
					"warm_count": null,
					"warm_enabled": null,
					"warm_type": null,
					"zone_awareness_config": [],
					"zone_awareness_enabled": null,
				}],
				"cognito_options": [],
				"domain_name": "testdomain",
				"elasticsearch_version": "6.3",
				"log_publishing_options": [],
				"snapshot_options": [{"automated_snapshot_start_hour": 23}],
				"tags": {"Domain": "TestDomain"},
				"timeouts": null,
				"vpc_options": [],
			},
		},
		{
			"address": "aws_elasticsearch_domain.valid-es",
			"mode": "managed",
			"type": "aws_elasticsearch_domain",
			"name": "valid-es",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"cluster_config": [{
					"dedicated_master_count": null,
					"dedicated_master_enabled": false,
					"dedicated_master_type": null,
					"instance_count": 1,
					"instance_type": "m4.large.elasticsearch",
					"warm_count": null,
					"warm_enabled": null,
					"warm_type": null,
					"zone_awareness_config": [],
					"zone_awareness_enabled": null,
				}],
				"cognito_options": [],
				"domain_name": "testdomain",
				"elasticsearch_version": "6.3",
				"log_publishing_options": [],
				"snapshot_options": [{"automated_snapshot_start_hour": 23}],
				"tags": {"Domain": "TestDomain"},
				"timeouts": null,
				"vpc_options": [{}],
			},
		},
		{
			"address": "aws_iam_service_linked_role.es",
			"mode": "managed",
			"type": "aws_iam_service_linked_role",
			"name": "es",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"aws_service_name": "es.amazonaws.com",
				"custom_suffix": null,
				"description": null,
			},
		},
		{
			"address": "aws_security_group.es",
			"mode": "managed",
			"type": "aws_security_group",
			"name": "es",
			"provider_name": "aws",
			"schema_version": 1,
			"values": {
				"description": "Managed by Terraform",
				"ingress": [{
					"cidr_blocks": ["10.0.0.0/16"],
					"description": "",
					"from_port": 443,
					"ipv6_cidr_blocks": [],
					"prefix_list_ids": [],
					"protocol": "tcp",
					"security_groups": [],
					"self": false,
					"to_port": 443,
				}],
				"name": "test-elasticsearch-testdomain",
				"name_prefix": null,
				"revoke_rules_on_delete": false,
				"tags": null,
				"timeouts": null,
			},
		},
		{
			"address": "aws_subnet.main",
			"mode": "managed",
			"type": "aws_subnet",
			"name": "main",
			"provider_name": "aws",
			"schema_version": 1,
			"values": {
				"assign_ipv6_address_on_creation": false,
				"cidr_block": "10.0.0.0/16",
				"map_public_ip_on_launch": false,
				"outpost_arn": null,
				"tags": {"Name": "Main"},
				"timeouts": null,
			},
		},
		{
			"address": "aws_vpc.main",
			"mode": "managed",
			"type": "aws_vpc",
			"name": "main",
			"provider_name": "aws",
			"schema_version": 1,
			"values": {
				"assign_generated_ipv6_cidr_block": false,
				"cidr_block": "10.0.0.0/16",
				"enable_dns_support": true,
				"instance_tenancy": "default",
				"tags": {"Name": "main"},
			},
		},
	]}},
	"resource_changes": [
		{
			"address": "aws_elasticsearch_domain.invalid-es",
			"mode": "managed",
			"type": "aws_elasticsearch_domain",
			"name": "invalid-es",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"cluster_config": [{
						"dedicated_master_count": null,
						"dedicated_master_enabled": false,
						"dedicated_master_type": null,
						"instance_count": 1,
						"instance_type": "m4.large.elasticsearch",
						"warm_count": null,
						"warm_enabled": null,
						"warm_type": null,
						"zone_awareness_config": [],
						"zone_awareness_enabled": null,
					}],
					"cognito_options": [],
					"domain_name": "testdomain",
					"elasticsearch_version": "6.3",
					"log_publishing_options": [],
					"snapshot_options": [{"automated_snapshot_start_hour": 23}],
					"tags": {"Domain": "TestDomain"},
					"timeouts": null,
					"vpc_options": [],
				},
				"after_unknown": {
					"access_policies": true,
					"advanced_options": true,
					"advanced_security_options": true,
					"arn": true,
					"cluster_config": [{"zone_awareness_config": []}],
					"cognito_options": [],
					"domain_endpoint_options": true,
					"domain_id": true,
					"ebs_options": true,
					"encrypt_at_rest": true,
					"endpoint": true,
					"id": true,
					"kibana_endpoint": true,
					"log_publishing_options": [],
					"node_to_node_encryption": true,
					"snapshot_options": [{}],
					"tags": {},
					"vpc_options": [],
				},
			},
		},
		{
			"address": "aws_elasticsearch_domain.valid-es",
			"mode": "managed",
			"type": "aws_elasticsearch_domain",
			"name": "valid-es",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"cluster_config": [{
						"dedicated_master_count": null,
						"dedicated_master_enabled": false,
						"dedicated_master_type": null,
						"instance_count": 1,
						"instance_type": "m4.large.elasticsearch",
						"warm_count": null,
						"warm_enabled": null,
						"warm_type": null,
						"zone_awareness_config": [],
						"zone_awareness_enabled": null,
					}],
					"cognito_options": [],
					"domain_name": "testdomain",
					"elasticsearch_version": "6.3",
					"log_publishing_options": [],
					"snapshot_options": [{"automated_snapshot_start_hour": 23}],
					"tags": {"Domain": "TestDomain"},
					"timeouts": null,
					"vpc_options": [{}],
				},
				"after_unknown": {
					"access_policies": true,
					"advanced_options": true,
					"advanced_security_options": true,
					"arn": true,
					"cluster_config": [{"zone_awareness_config": []}],
					"cognito_options": [],
					"domain_endpoint_options": true,
					"domain_id": true,
					"ebs_options": true,
					"encrypt_at_rest": true,
					"endpoint": true,
					"id": true,
					"kibana_endpoint": true,
					"log_publishing_options": [],
					"node_to_node_encryption": true,
					"snapshot_options": [{}],
					"tags": {},
					"vpc_options": [{
						"availability_zones": true,
						"security_group_ids": true,
						"subnet_ids": true,
						"vpc_id": true,
					}],
				},
			},
		},
		{
			"address": "aws_iam_service_linked_role.es",
			"mode": "managed",
			"type": "aws_iam_service_linked_role",
			"name": "es",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"aws_service_name": "es.amazonaws.com",
					"custom_suffix": null,
					"description": null,
				},
				"after_unknown": {
					"arn": true,
					"create_date": true,
					"id": true,
					"name": true,
					"path": true,
					"unique_id": true,
				},
			},
		},
		{
			"address": "aws_security_group.es",
			"mode": "managed",
			"type": "aws_security_group",
			"name": "es",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"description": "Managed by Terraform",
					"ingress": [{
						"cidr_blocks": ["10.0.0.0/16"],
						"description": "",
						"from_port": 443,
						"ipv6_cidr_blocks": [],
						"prefix_list_ids": [],
						"protocol": "tcp",
						"security_groups": [],
						"self": false,
						"to_port": 443,
					}],
					"name": "test-elasticsearch-testdomain",
					"name_prefix": null,
					"revoke_rules_on_delete": false,
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {
					"arn": true,
					"egress": true,
					"id": true,
					"ingress": [{
						"cidr_blocks": [false],
						"ipv6_cidr_blocks": [],
						"prefix_list_ids": [],
						"security_groups": [],
					}],
					"owner_id": true,
					"vpc_id": true,
				},
			},
		},
		{
			"address": "aws_subnet.main",
			"mode": "managed",
			"type": "aws_subnet",
			"name": "main",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"assign_ipv6_address_on_creation": false,
					"cidr_block": "10.0.0.0/16",
					"map_public_ip_on_launch": false,
					"outpost_arn": null,
					"tags": {"Name": "Main"},
					"timeouts": null,
				},
				"after_unknown": {
					"arn": true,
					"availability_zone": true,
					"availability_zone_id": true,
					"id": true,
					"ipv6_cidr_block": true,
					"ipv6_cidr_block_association_id": true,
					"owner_id": true,
					"tags": {},
					"vpc_id": true,
				},
			},
		},
		{
			"address": "aws_vpc.main",
			"mode": "managed",
			"type": "aws_vpc",
			"name": "main",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"assign_generated_ipv6_cidr_block": false,
					"cidr_block": "10.0.0.0/16",
					"enable_dns_support": true,
					"instance_tenancy": "default",
					"tags": {"Name": "main"},
				},
				"after_unknown": {
					"arn": true,
					"default_network_acl_id": true,
					"default_route_table_id": true,
					"default_security_group_id": true,
					"dhcp_options_id": true,
					"enable_classiclink": true,
					"enable_classiclink_dns_support": true,
					"enable_dns_hostnames": true,
					"id": true,
					"ipv6_association_id": true,
					"ipv6_cidr_block": true,
					"main_route_table_id": true,
					"owner_id": true,
					"tags": {},
				},
			},
		},
	],
	"configuration": {
		"provider_config": {"aws": {
			"name": "aws",
			"expressions": {
				"profile": {"constant_value": "saml"},
				"region": {"constant_value": "us-east-1"},
				"shared_credentials_file": {"constant_value": "~/.aws/creds"},
			},
		}},
		"root_module": {"resources": [
			{
				"address": "aws_elasticsearch_domain.invalid-es",
				"mode": "managed",
				"type": "aws_elasticsearch_domain",
				"name": "invalid-es",
				"provider_config_key": "aws",
				"expressions": {
					"cluster_config": [{"instance_type": {"constant_value": "m4.large.elasticsearch"}}],
					"domain_name": {"constant_value": "testdomain"},
					"elasticsearch_version": {"constant_value": "6.3"},
					"snapshot_options": [{"automated_snapshot_start_hour": {"constant_value": 23}}],
					"tags": {"constant_value": {"Domain": "TestDomain"}},
				},
				"schema_version": 0,
				"depends_on": ["aws_iam_service_linked_role.es"],
			},
			{
				"address": "aws_elasticsearch_domain.valid-es",
				"mode": "managed",
				"type": "aws_elasticsearch_domain",
				"name": "valid-es",
				"provider_config_key": "aws",
				"expressions": {
					"cluster_config": [{"instance_type": {"constant_value": "m4.large.elasticsearch"}}],
					"domain_name": {"constant_value": "testdomain"},
					"elasticsearch_version": {"constant_value": "6.3"},
					"snapshot_options": [{"automated_snapshot_start_hour": {"constant_value": 23}}],
					"tags": {"constant_value": {"Domain": "TestDomain"}},
					"vpc_options": [{
						"security_group_ids": {"references": ["aws_security_group.es"]},
						"subnet_ids": {"references": ["aws_subnet.main"]},
					}],
				},
				"schema_version": 0,
				"depends_on": ["aws_iam_service_linked_role.es"],
			},
			{
				"address": "aws_iam_service_linked_role.es",
				"mode": "managed",
				"type": "aws_iam_service_linked_role",
				"name": "es",
				"provider_config_key": "aws",
				"expressions": {"aws_service_name": {"constant_value": "es.amazonaws.com"}},
				"schema_version": 0,
			},
			{
				"address": "aws_security_group.es",
				"mode": "managed",
				"type": "aws_security_group",
				"name": "es",
				"provider_config_key": "aws",
				"expressions": {
					"description": {"constant_value": "Managed by Terraform"},
					"name": {"constant_value": "test-elasticsearch-testdomain"},
					"vpc_id": {"references": ["aws_vpc.main"]},
				},
				"schema_version": 1,
			},
			{
				"address": "aws_subnet.main",
				"mode": "managed",
				"type": "aws_subnet",
				"name": "main",
				"provider_config_key": "aws",
				"expressions": {
					"cidr_block": {"constant_value": "10.0.0.0/16"},
					"tags": {"constant_value": {"Name": "Main"}},
					"vpc_id": {"references": ["aws_vpc.main"]},
				},
				"schema_version": 1,
			},
			{
				"address": "aws_vpc.main",
				"mode": "managed",
				"type": "aws_vpc",
				"name": "main",
				"provider_config_key": "aws",
				"expressions": {
					"cidr_block": {"constant_value": "10.0.0.0/16"},
					"instance_tenancy": {"constant_value": "default"},
					"tags": {"constant_value": {"Name": "main"}},
				},
				"schema_version": 1,
			},
		]},
	},
}
