# Rego test for CloudFront HTTPS Connection
# Validating rule cloudfront_logging: Deny CloudFront Distributions that do not have logging enabled

package rules.cloudfront_logging

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

test_cloudfront_logging {
	pol := policy with input as mock_input
	resources := {p.id: p.valid | pol[p]}

	resources["aws_cloudfront_distribution.valid"] == true
	resources["aws_cloudfront_distribution.invalid"] == false
}

# Mock input is generated plan for cloudfront_logging.tf
mock_plan_input = {
	"format_version": "0.1",
	"terraform_version": "0.12.28",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "aws_cloudfront_distribution.invalid",
			"mode": "managed",
			"type": "aws_cloudfront_distribution",
			"name": "invalid",
			"provider_name": "aws",
			"schema_version": 1,
			"values": {
				"aliases": null,
				"comment": null,
				"custom_error_response": [],
				"default_cache_behavior": [{
					"allowed_methods": [
						"DELETE",
						"GET",
						"HEAD",
						"OPTIONS",
						"PATCH",
						"POST",
						"PUT",
					],
					"cached_methods": [
						"GET",
						"HEAD",
					],
					"compress": false,
					"default_ttl": 86400,
					"field_level_encryption_id": null,
					"forwarded_values": [{
						"cookies": [{
							"forward": "none",
							"whitelisted_names": null,
						}],
						"headers": null,
						"query_string": false,
						"query_string_cache_keys": null,
					}],
					"lambda_function_association": [],
					"max_ttl": 31536000,
					"min_ttl": 0,
					"smooth_streaming": null,
					"target_origin_id": "myS3Origin",
					"trusted_signers": null,
					"viewer_protocol_policy": "allow-all",
				}],
				"default_root_object": null,
				"enabled": true,
				"http_version": "http2",
				"is_ipv6_enabled": false,
				"logging_config": [],
				"ordered_cache_behavior": [],
				"origin": [{
					"custom_header": [],
					"custom_origin_config": [],
					"origin_id": "myS3Origin",
					"origin_path": "",
					"s3_origin_config": [{"origin_access_identity": "origin-access-identity/cloudfront/ABCDEFG1234567"}],
				}],
				"origin_group": [],
				"price_class": "PriceClass_All",
				"restrictions": [{"geo_restriction": [{
					"locations": [
						"CA",
						"DE",
						"GB",
						"US",
					],
					"restriction_type": "whitelist",
				}]}],
				"retain_on_delete": false,
				"tags": null,
				"viewer_certificate": [{
					"acm_certificate_arn": null,
					"cloudfront_default_certificate": true,
					"iam_certificate_id": null,
					"minimum_protocol_version": "TLSv1",
					"ssl_support_method": null,
				}],
				"wait_for_deployment": true,
				"web_acl_id": null,
			},
		},
		{
			"address": "aws_cloudfront_distribution.valid",
			"mode": "managed",
			"type": "aws_cloudfront_distribution",
			"name": "valid",
			"provider_name": "aws",
			"schema_version": 1,
			"values": {
				"aliases": null,
				"comment": null,
				"custom_error_response": [],
				"default_cache_behavior": [{
					"allowed_methods": [
						"DELETE",
						"GET",
						"HEAD",
						"OPTIONS",
						"PATCH",
						"POST",
						"PUT",
					],
					"cached_methods": [
						"GET",
						"HEAD",
					],
					"compress": false,
					"default_ttl": 86400,
					"field_level_encryption_id": null,
					"forwarded_values": [{
						"cookies": [{
							"forward": "none",
							"whitelisted_names": null,
						}],
						"headers": null,
						"query_string": false,
						"query_string_cache_keys": null,
					}],
					"lambda_function_association": [],
					"max_ttl": 31536000,
					"min_ttl": 0,
					"smooth_streaming": null,
					"target_origin_id": "myS3Origin",
					"trusted_signers": null,
					"viewer_protocol_policy": "allow-all",
				}],
				"default_root_object": null,
				"enabled": true,
				"http_version": "http2",
				"is_ipv6_enabled": false,
				"logging_config": [{
					"bucket": "mylogs.s3.amazonaws.com",
					"include_cookies": false,
					"prefix": "myprefix",
				}],
				"ordered_cache_behavior": [],
				"origin": [{
					"custom_header": [],
					"custom_origin_config": [],
					"origin_id": "myS3Origin",
					"origin_path": "",
					"s3_origin_config": [{"origin_access_identity": "origin-access-identity/cloudfront/ABCDEFG1234567"}],
				}],
				"origin_group": [],
				"price_class": "PriceClass_All",
				"restrictions": [{"geo_restriction": [{
					"locations": [
						"CA",
						"DE",
						"GB",
						"US",
					],
					"restriction_type": "whitelist",
				}]}],
				"retain_on_delete": false,
				"tags": null,
				"viewer_certificate": [{
					"acm_certificate_arn": null,
					"cloudfront_default_certificate": true,
					"iam_certificate_id": null,
					"minimum_protocol_version": "TLSv1",
					"ssl_support_method": null,
				}],
				"wait_for_deployment": true,
				"web_acl_id": null,
			},
		},
		{
			"address": "aws_s3_bucket.a",
			"mode": "managed",
			"type": "aws_s3_bucket",
			"name": "a",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"acl": "private",
				"bucket": "mybucket",
				"bucket_prefix": null,
				"cors_rule": [],
				"force_destroy": false,
				"grant": [],
				"lifecycle_rule": [],
				"logging": [],
				"object_lock_configuration": [],
				"policy": null,
				"replication_configuration": [],
				"server_side_encryption_configuration": [],
				"tags": {"Name": "My bucket"},
				"website": [],
			},
		},
		{
			"address": "aws_s3_bucket.b",
			"mode": "managed",
			"type": "aws_s3_bucket",
			"name": "b",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"acl": "private",
				"bucket": "mybucket",
				"bucket_prefix": null,
				"cors_rule": [],
				"force_destroy": false,
				"grant": [],
				"lifecycle_rule": [],
				"logging": [],
				"object_lock_configuration": [],
				"policy": null,
				"replication_configuration": [],
				"server_side_encryption_configuration": [],
				"tags": {"Name": "My bucket"},
				"website": [],
			},
		},
	]}},
	"resource_changes": [
		{
			"address": "aws_cloudfront_distribution.invalid",
			"mode": "managed",
			"type": "aws_cloudfront_distribution",
			"name": "invalid",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"aliases": null,
					"comment": null,
					"custom_error_response": [],
					"default_cache_behavior": [{
						"allowed_methods": [
							"DELETE",
							"GET",
							"HEAD",
							"OPTIONS",
							"PATCH",
							"POST",
							"PUT",
						],
						"cached_methods": [
							"GET",
							"HEAD",
						],
						"compress": false,
						"default_ttl": 86400,
						"field_level_encryption_id": null,
						"forwarded_values": [{
							"cookies": [{
								"forward": "none",
								"whitelisted_names": null,
							}],
							"headers": null,
							"query_string": false,
							"query_string_cache_keys": null,
						}],
						"lambda_function_association": [],
						"max_ttl": 31536000,
						"min_ttl": 0,
						"smooth_streaming": null,
						"target_origin_id": "myS3Origin",
						"trusted_signers": null,
						"viewer_protocol_policy": "allow-all",
					}],
					"default_root_object": null,
					"enabled": true,
					"http_version": "http2",
					"is_ipv6_enabled": false,
					"logging_config": [],
					"ordered_cache_behavior": [],
					"origin": [{
						"custom_header": [],
						"custom_origin_config": [],
						"origin_id": "myS3Origin",
						"origin_path": "",
						"s3_origin_config": [{"origin_access_identity": "origin-access-identity/cloudfront/ABCDEFG1234567"}],
					}],
					"origin_group": [],
					"price_class": "PriceClass_All",
					"restrictions": [{"geo_restriction": [{
						"locations": [
							"CA",
							"DE",
							"GB",
							"US",
						],
						"restriction_type": "whitelist",
					}]}],
					"retain_on_delete": false,
					"tags": null,
					"viewer_certificate": [{
						"acm_certificate_arn": null,
						"cloudfront_default_certificate": true,
						"iam_certificate_id": null,
						"minimum_protocol_version": "TLSv1",
						"ssl_support_method": null,
					}],
					"wait_for_deployment": true,
					"web_acl_id": null,
				},
				"after_unknown": {
					"arn": true,
					"caller_reference": true,
					"custom_error_response": [],
					"default_cache_behavior": [{
						"allowed_methods": [
							false,
							false,
							false,
							false,
							false,
							false,
							false,
						],
						"cached_methods": [
							false,
							false,
						],
						"forwarded_values": [{"cookies": [{}]}],
						"lambda_function_association": [],
					}],
					"domain_name": true,
					"etag": true,
					"hosted_zone_id": true,
					"id": true,
					"in_progress_validation_batches": true,
					"last_modified_time": true,
					"logging_config": [],
					"ordered_cache_behavior": [],
					"origin": [{
						"custom_header": [],
						"custom_origin_config": [],
						"domain_name": true,
						"s3_origin_config": [{}],
					}],
					"origin_group": [],
					"restrictions": [{"geo_restriction": [{"locations": [
						false,
						false,
						false,
						false,
					]}]}],
					"status": true,
					"trusted_signers": true,
					"viewer_certificate": [{}],
				},
			},
		},
		{
			"address": "aws_cloudfront_distribution.valid",
			"mode": "managed",
			"type": "aws_cloudfront_distribution",
			"name": "valid",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"aliases": null,
					"comment": null,
					"custom_error_response": [],
					"default_cache_behavior": [{
						"allowed_methods": [
							"DELETE",
							"GET",
							"HEAD",
							"OPTIONS",
							"PATCH",
							"POST",
							"PUT",
						],
						"cached_methods": [
							"GET",
							"HEAD",
						],
						"compress": false,
						"default_ttl": 86400,
						"field_level_encryption_id": null,
						"forwarded_values": [{
							"cookies": [{
								"forward": "none",
								"whitelisted_names": null,
							}],
							"headers": null,
							"query_string": false,
							"query_string_cache_keys": null,
						}],
						"lambda_function_association": [],
						"max_ttl": 31536000,
						"min_ttl": 0,
						"smooth_streaming": null,
						"target_origin_id": "myS3Origin",
						"trusted_signers": null,
						"viewer_protocol_policy": "allow-all",
					}],
					"default_root_object": null,
					"enabled": true,
					"http_version": "http2",
					"is_ipv6_enabled": false,
					"logging_config": [{
						"bucket": "mylogs.s3.amazonaws.com",
						"include_cookies": false,
						"prefix": "myprefix",
					}],
					"ordered_cache_behavior": [],
					"origin": [{
						"custom_header": [],
						"custom_origin_config": [],
						"origin_id": "myS3Origin",
						"origin_path": "",
						"s3_origin_config": [{"origin_access_identity": "origin-access-identity/cloudfront/ABCDEFG1234567"}],
					}],
					"origin_group": [],
					"price_class": "PriceClass_All",
					"restrictions": [{"geo_restriction": [{
						"locations": [
							"CA",
							"DE",
							"GB",
							"US",
						],
						"restriction_type": "whitelist",
					}]}],
					"retain_on_delete": false,
					"tags": null,
					"viewer_certificate": [{
						"acm_certificate_arn": null,
						"cloudfront_default_certificate": true,
						"iam_certificate_id": null,
						"minimum_protocol_version": "TLSv1",
						"ssl_support_method": null,
					}],
					"wait_for_deployment": true,
					"web_acl_id": null,
				},
				"after_unknown": {
					"arn": true,
					"caller_reference": true,
					"custom_error_response": [],
					"default_cache_behavior": [{
						"allowed_methods": [
							false,
							false,
							false,
							false,
							false,
							false,
							false,
						],
						"cached_methods": [
							false,
							false,
						],
						"forwarded_values": [{"cookies": [{}]}],
						"lambda_function_association": [],
					}],
					"domain_name": true,
					"etag": true,
					"hosted_zone_id": true,
					"id": true,
					"in_progress_validation_batches": true,
					"last_modified_time": true,
					"logging_config": [{}],
					"ordered_cache_behavior": [],
					"origin": [{
						"custom_header": [],
						"custom_origin_config": [],
						"domain_name": true,
						"s3_origin_config": [{}],
					}],
					"origin_group": [],
					"restrictions": [{"geo_restriction": [{"locations": [
						false,
						false,
						false,
						false,
					]}]}],
					"status": true,
					"trusted_signers": true,
					"viewer_certificate": [{}],
				},
			},
		},
		{
			"address": "aws_s3_bucket.a",
			"mode": "managed",
			"type": "aws_s3_bucket",
			"name": "a",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"acl": "private",
					"bucket": "mybucket",
					"bucket_prefix": null,
					"cors_rule": [],
					"force_destroy": false,
					"grant": [],
					"lifecycle_rule": [],
					"logging": [],
					"object_lock_configuration": [],
					"policy": null,
					"replication_configuration": [],
					"server_side_encryption_configuration": [],
					"tags": {"Name": "My bucket"},
					"website": [],
				},
				"after_unknown": {
					"acceleration_status": true,
					"arn": true,
					"bucket_domain_name": true,
					"bucket_regional_domain_name": true,
					"cors_rule": [],
					"grant": [],
					"hosted_zone_id": true,
					"id": true,
					"lifecycle_rule": [],
					"logging": [],
					"object_lock_configuration": [],
					"region": true,
					"replication_configuration": [],
					"request_payer": true,
					"server_side_encryption_configuration": [],
					"tags": {},
					"versioning": true,
					"website": [],
					"website_domain": true,
					"website_endpoint": true,
				},
			},
		},
		{
			"address": "aws_s3_bucket.b",
			"mode": "managed",
			"type": "aws_s3_bucket",
			"name": "b",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"acl": "private",
					"bucket": "mybucket",
					"bucket_prefix": null,
					"cors_rule": [],
					"force_destroy": false,
					"grant": [],
					"lifecycle_rule": [],
					"logging": [],
					"object_lock_configuration": [],
					"policy": null,
					"replication_configuration": [],
					"server_side_encryption_configuration": [],
					"tags": {"Name": "My bucket"},
					"website": [],
				},
				"after_unknown": {
					"acceleration_status": true,
					"arn": true,
					"bucket_domain_name": true,
					"bucket_regional_domain_name": true,
					"cors_rule": [],
					"grant": [],
					"hosted_zone_id": true,
					"id": true,
					"lifecycle_rule": [],
					"logging": [],
					"object_lock_configuration": [],
					"region": true,
					"replication_configuration": [],
					"request_payer": true,
					"server_side_encryption_configuration": [],
					"tags": {},
					"versioning": true,
					"website": [],
					"website_domain": true,
					"website_endpoint": true,
				},
			},
		},
	],
	"configuration": {
		"provider_config": {"aws": {
			"name": "aws",
			"expressions": {
				"profile": {"constant_value": "saml"},
				"region": {"constant_value": "us-east-1"},
				"shared_credentials_file": {"constant_value": "~/.aws/creds"},
			},
		}},
		"root_module": {"resources": [
			{
				"address": "aws_cloudfront_distribution.invalid",
				"mode": "managed",
				"type": "aws_cloudfront_distribution",
				"name": "invalid",
				"provider_config_key": "aws",
				"expressions": {
					"default_cache_behavior": [{
						"allowed_methods": {"constant_value": [
							"DELETE",
							"GET",
							"HEAD",
							"OPTIONS",
							"PATCH",
							"POST",
							"PUT",
						]},
						"cached_methods": {"constant_value": [
							"GET",
							"HEAD",
						]},
						"forwarded_values": [{
							"cookies": [{"forward": {"constant_value": "none"}}],
							"query_string": {"constant_value": false},
						}],
						"target_origin_id": {"references": ["local.s3_origin_id"]},
						"viewer_protocol_policy": {"constant_value": "allow-all"},
					}],
					"enabled": {"constant_value": true},
					"origin": [{
						"domain_name": {"references": ["aws_s3_bucket.b"]},
						"origin_id": {"references": ["local.s3_origin_id"]},
						"s3_origin_config": [{"origin_access_identity": {"constant_value": "origin-access-identity/cloudfront/ABCDEFG1234567"}}],
					}],
					"restrictions": [{"geo_restriction": [{
						"locations": {"constant_value": [
							"US",
							"CA",
							"GB",
							"DE",
						]},
						"restriction_type": {"constant_value": "whitelist"},
					}]}],
					"viewer_certificate": [{"cloudfront_default_certificate": {"constant_value": true}}],
				},
				"schema_version": 1,
			},
			{
				"address": "aws_cloudfront_distribution.valid",
				"mode": "managed",
				"type": "aws_cloudfront_distribution",
				"name": "valid",
				"provider_config_key": "aws",
				"expressions": {
					"default_cache_behavior": [{
						"allowed_methods": {"constant_value": [
							"DELETE",
							"GET",
							"HEAD",
							"OPTIONS",
							"PATCH",
							"POST",
							"PUT",
						]},
						"cached_methods": {"constant_value": [
							"GET",
							"HEAD",
						]},
						"forwarded_values": [{
							"cookies": [{"forward": {"constant_value": "none"}}],
							"query_string": {"constant_value": false},
						}],
						"target_origin_id": {"references": ["local.s3_origin_id"]},
						"viewer_protocol_policy": {"constant_value": "allow-all"},
					}],
					"enabled": {"constant_value": true},
					"logging_config": [{
						"bucket": {"constant_value": "mylogs.s3.amazonaws.com"},
						"include_cookies": {"constant_value": false},
						"prefix": {"constant_value": "myprefix"},
					}],
					"origin": [{
						"domain_name": {"references": ["aws_s3_bucket.a"]},
						"origin_id": {"references": ["local.s3_origin_id_2"]},
						"s3_origin_config": [{"origin_access_identity": {"constant_value": "origin-access-identity/cloudfront/ABCDEFG1234567"}}],
					}],
					"restrictions": [{"geo_restriction": [{
						"locations": {"constant_value": [
							"US",
							"CA",
							"GB",
							"DE",
						]},
						"restriction_type": {"constant_value": "whitelist"},
					}]}],
					"viewer_certificate": [{"cloudfront_default_certificate": {"constant_value": true}}],
				},
				"schema_version": 1,
			},
			{
				"address": "aws_s3_bucket.a",
				"mode": "managed",
				"type": "aws_s3_bucket",
				"name": "a",
				"provider_config_key": "aws",
				"expressions": {
					"acl": {"constant_value": "private"},
					"bucket": {"constant_value": "mybucket"},
					"tags": {"constant_value": {"Name": "My bucket"}},
				},
				"schema_version": 0,
			},
			{
				"address": "aws_s3_bucket.b",
				"mode": "managed",
				"type": "aws_s3_bucket",
				"name": "b",
				"provider_config_key": "aws",
				"expressions": {
					"acl": {"constant_value": "private"},
					"bucket": {"constant_value": "mybucket"},
					"tags": {"constant_value": {"Name": "My bucket"}},
				},
				"schema_version": 0,
			},
		]},
	},
}
