# Purpose: This file tests whether the alb_access_logs.rego accurately denies/accepts 
# compliant application load balancers
package rules.alb_access_logging

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

test_alb_access_logging {
	pol := policy with input as mock_input
	resources := {p.id: p.valid | pol[p]}

	resources["aws_lb.valid_logs"] == true
	resources["aws_lb.invalid_logs"] == false
}

# Mock input is generated plan for alb_access_logs.rego
mock_plan_input = {
	"format_version": "0.1",
	"terraform_version": "0.12.28",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "aws_lb.invalid_logs",
			"mode": "managed",
			"type": "aws_lb",
			"name": "invalid_logs",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"access_logs": [],
				"drop_invalid_header_fields": false,
				"enable_cross_zone_load_balancing": null,
				"enable_deletion_protection": false,
				"enable_http2": true,
				"idle_timeout": 60,
				"internal": false,
				"load_balancer_type": "application",
				"name": "test-lb-tf",
				"name_prefix": null,
				"tags": {"Environment": "production"},
				"timeouts": null,
			},
		},
		{
			"address": "aws_lb.valid_logs",
			"mode": "managed",
			"type": "aws_lb",
			"name": "valid_logs",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"access_logs": [{
					"bucket": "my-tf-test-bucket",
					"enabled": true,
					"prefix": "test-lb",
				}],
				"drop_invalid_header_fields": false,
				"enable_cross_zone_load_balancing": null,
				"enable_deletion_protection": true,
				"enable_http2": true,
				"idle_timeout": 60,
				"internal": false,
				"load_balancer_type": "application",
				"name": "test-lb-tf",
				"name_prefix": null,
				"tags": {"Environment": "production"},
				"timeouts": null,
			},
		},
		{
			"address": "aws_s3_bucket.lb_logs",
			"mode": "managed",
			"type": "aws_s3_bucket",
			"name": "lb_logs",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"acl": "private",
				"bucket": "my-tf-test-bucket",
				"bucket_prefix": null,
				"cors_rule": [],
				"force_destroy": false,
				"grant": [],
				"lifecycle_rule": [],
				"logging": [],
				"object_lock_configuration": [],
				"policy": null,
				"replication_configuration": [],
				"server_side_encryption_configuration": [],
				"tags": {
					"Environment": "Dev",
					"Name": "My bucket",
				},
				"website": [],
			},
		},
	]}},
	"resource_changes": [
		{
			"address": "aws_lb.invalid_logs",
			"mode": "managed",
			"type": "aws_lb",
			"name": "invalid_logs",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"access_logs": [],
					"drop_invalid_header_fields": false,
					"enable_cross_zone_load_balancing": null,
					"enable_deletion_protection": false,
					"enable_http2": true,
					"idle_timeout": 60,
					"internal": false,
					"load_balancer_type": "application",
					"name": "test-lb-tf",
					"name_prefix": null,
					"tags": {"Environment": "production"},
					"timeouts": null,
				},
				"after_unknown": {
					"access_logs": [],
					"arn": true,
					"arn_suffix": true,
					"dns_name": true,
					"id": true,
					"ip_address_type": true,
					"security_groups": true,
					"subnet_mapping": true,
					"subnets": true,
					"tags": {},
					"vpc_id": true,
					"zone_id": true,
				},
			},
		},
		{
			"address": "aws_lb.valid_logs",
			"mode": "managed",
			"type": "aws_lb",
			"name": "valid_logs",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"access_logs": [{
						"bucket": "my-tf-test-bucket",
						"enabled": true,
						"prefix": "test-lb",
					}],
					"drop_invalid_header_fields": false,
					"enable_cross_zone_load_balancing": null,
					"enable_deletion_protection": true,
					"enable_http2": true,
					"idle_timeout": 60,
					"internal": false,
					"load_balancer_type": "application",
					"name": "test-lb-tf",
					"name_prefix": null,
					"tags": {"Environment": "production"},
					"timeouts": null,
				},
				"after_unknown": {
					"access_logs": [{}],
					"arn": true,
					"arn_suffix": true,
					"dns_name": true,
					"id": true,
					"ip_address_type": true,
					"security_groups": true,
					"subnet_mapping": true,
					"subnets": true,
					"tags": {},
					"vpc_id": true,
					"zone_id": true,
				},
			},
		},
		{
			"address": "aws_s3_bucket.lb_logs",
			"mode": "managed",
			"type": "aws_s3_bucket",
			"name": "lb_logs",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"acl": "private",
					"bucket": "my-tf-test-bucket",
					"bucket_prefix": null,
					"cors_rule": [],
					"force_destroy": false,
					"grant": [],
					"lifecycle_rule": [],
					"logging": [],
					"object_lock_configuration": [],
					"policy": null,
					"replication_configuration": [],
					"server_side_encryption_configuration": [],
					"tags": {
						"Environment": "Dev",
						"Name": "My bucket",
					},
					"website": [],
				},
				"after_unknown": {
					"acceleration_status": true,
					"arn": true,
					"bucket_domain_name": true,
					"bucket_regional_domain_name": true,
					"cors_rule": [],
					"grant": [],
					"hosted_zone_id": true,
					"id": true,
					"lifecycle_rule": [],
					"logging": [],
					"object_lock_configuration": [],
					"region": true,
					"replication_configuration": [],
					"request_payer": true,
					"server_side_encryption_configuration": [],
					"tags": {},
					"versioning": true,
					"website": [],
					"website_domain": true,
					"website_endpoint": true,
				},
			},
		},
	],
	"configuration": {
		"provider_config": {"aws": {
			"name": "aws",
			"expressions": {
				"profile": {"constant_value": "saml"},
				"region": {"constant_value": "us-east-1"},
				"shared_credentials_file": {"constant_value": "~/.aws/creds"},
			},
		}},
		"root_module": {"resources": [
			{
				"address": "aws_lb.invalid_logs",
				"mode": "managed",
				"type": "aws_lb",
				"name": "invalid_logs",
				"provider_config_key": "aws",
				"expressions": {
					"internal": {"constant_value": false},
					"load_balancer_type": {"constant_value": "application"},
					"name": {"constant_value": "test-lb-tf"},
					"tags": {"constant_value": {"Environment": "production"}},
				},
				"schema_version": 0,
			},
			{
				"address": "aws_lb.valid_logs",
				"mode": "managed",
				"type": "aws_lb",
				"name": "valid_logs",
				"provider_config_key": "aws",
				"expressions": {
					"access_logs": [{
						"bucket": {"references": ["aws_s3_bucket.lb_logs"]},
						"enabled": {"constant_value": true},
						"prefix": {"constant_value": "test-lb"},
					}],
					"enable_deletion_protection": {"constant_value": true},
					"internal": {"constant_value": false},
					"load_balancer_type": {"constant_value": "application"},
					"name": {"constant_value": "test-lb-tf"},
					"tags": {"constant_value": {"Environment": "production"}},
				},
				"schema_version": 0,
			},
			{
				"address": "aws_s3_bucket.lb_logs",
				"mode": "managed",
				"type": "aws_s3_bucket",
				"name": "lb_logs",
				"provider_config_key": "aws",
				"expressions": {
					"acl": {"constant_value": "private"},
					"bucket": {"constant_value": "my-tf-test-bucket"},
					"tags": {"constant_value": {
						"Environment": "Dev",
						"Name": "My bucket",
					}},
				},
				"schema_version": 0,
			},
		]},
	},
}
