# Rego test for Cognitive Services Restricted Network Access
# Validating rule cognitive_services_restrict_network_access: Cognitive Services should have public network access denied and utilize firewall rules.
package rules.cognitive_services_restrict_network_access

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

test_restricted_network_access_cognitive_services {
	pol := policy with input as mock_input
	resources := {p.id: p.valid | pol[p]}

	resources["azurerm_cognitive_account.invalid"] == false
	resources["azurerm_cognitive_account.valid"] == true
}

# Mock input is generated plan for cognitive_services_restrict_network_access.tf
mock_plan_input = {
	"format_version": "0.1",
	"terraform_version": "1.0.0",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "azurerm_cognitive_account.invalid",
			"mode": "managed",
			"type": "azurerm_cognitive_account",
			"name": "invalid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"custom_subdomain_name": "example-account-invalid",
				"fqdns": null,
				"identity": [],
				"kind": "Face",
				"local_auth_enabled": true,
				"location": "westeurope",
				"metrics_advisor_aad_client_id": null,
				"metrics_advisor_aad_tenant_id": null,
				"metrics_advisor_super_user_name": null,
				"metrics_advisor_website_name": null,
				"name": "example-account-invalid",
				"network_acls": [{
					"default_action": "Allow",
					"ip_rules": null,
				}],
				"outbound_network_access_restrited": false,
				"public_network_access_enabled": true,
				"qna_runtime_endpoint": null,
				"resource_group_name": "example-resources",
				"sku_name": "S0",
				"storage": [],
				"tags": {"Acceptance": "Test"},
				"timeouts": null,
			},
		},
		{
			"address": "azurerm_cognitive_account.valid",
			"mode": "managed",
			"type": "azurerm_cognitive_account",
			"name": "valid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"custom_subdomain_name": "example-account-valid",
				"fqdns": null,
				"identity": [],
				"kind": "Face",
				"local_auth_enabled": true,
				"location": "westeurope",
				"metrics_advisor_aad_client_id": null,
				"metrics_advisor_aad_tenant_id": null,
				"metrics_advisor_super_user_name": null,
				"metrics_advisor_website_name": null,
				"name": "example-account-valid",
				"network_acls": [{
					"default_action": "Deny",
					"ip_rules": ["10.0.0.0/16"],
				}],
				"outbound_network_access_restrited": false,
				"public_network_access_enabled": true,
				"qna_runtime_endpoint": null,
				"resource_group_name": "example-resources",
				"sku_name": "S0",
				"storage": [],
				"tags": {"Acceptance": "Test"},
				"timeouts": null,
			},
		},
		{
			"address": "azurerm_resource_group.example",
			"mode": "managed",
			"type": "azurerm_resource_group",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"location": "westeurope",
				"name": "example-resources",
				"tags": null,
				"timeouts": null,
			},
		},
	]}},
	"resource_changes": [
		{
			"address": "azurerm_cognitive_account.invalid",
			"mode": "managed",
			"type": "azurerm_cognitive_account",
			"name": "invalid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"custom_subdomain_name": "example-account-invalid",
					"fqdns": null,
					"identity": [],
					"kind": "Face",
					"local_auth_enabled": true,
					"location": "westeurope",
					"metrics_advisor_aad_client_id": null,
					"metrics_advisor_aad_tenant_id": null,
					"metrics_advisor_super_user_name": null,
					"metrics_advisor_website_name": null,
					"name": "example-account-invalid",
					"network_acls": [{
						"default_action": "Allow",
						"ip_rules": null,
					}],
					"outbound_network_access_restrited": false,
					"public_network_access_enabled": true,
					"qna_runtime_endpoint": null,
					"resource_group_name": "example-resources",
					"sku_name": "S0",
					"storage": [],
					"tags": {"Acceptance": "Test"},
					"timeouts": null,
				},
				"after_unknown": {
					"endpoint": true,
					"id": true,
					"identity": [],
					"network_acls": [{
						"virtual_network_rules": true,
						"virtual_network_subnet_ids": true,
					}],
					"primary_access_key": true,
					"secondary_access_key": true,
					"storage": [],
					"tags": {},
				},
				"before_sensitive": false,
				"after_sensitive": {
					"identity": [],
					"network_acls": [{
						"virtual_network_rules": [],
						"virtual_network_subnet_ids": [],
					}],
					"primary_access_key": true,
					"secondary_access_key": true,
					"storage": [],
					"tags": {},
				},
			},
		},
		{
			"address": "azurerm_cognitive_account.valid",
			"mode": "managed",
			"type": "azurerm_cognitive_account",
			"name": "valid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"custom_subdomain_name": "example-account-valid",
					"fqdns": null,
					"identity": [],
					"kind": "Face",
					"local_auth_enabled": true,
					"location": "westeurope",
					"metrics_advisor_aad_client_id": null,
					"metrics_advisor_aad_tenant_id": null,
					"metrics_advisor_super_user_name": null,
					"metrics_advisor_website_name": null,
					"name": "example-account-valid",
					"network_acls": [{
						"default_action": "Deny",
						"ip_rules": ["10.0.0.0/16"],
					}],
					"outbound_network_access_restrited": false,
					"public_network_access_enabled": true,
					"qna_runtime_endpoint": null,
					"resource_group_name": "example-resources",
					"sku_name": "S0",
					"storage": [],
					"tags": {"Acceptance": "Test"},
					"timeouts": null,
				},
				"after_unknown": {
					"endpoint": true,
					"id": true,
					"identity": [],
					"network_acls": [{
						"ip_rules": [false],
						"virtual_network_rules": true,
						"virtual_network_subnet_ids": true,
					}],
					"primary_access_key": true,
					"secondary_access_key": true,
					"storage": [],
					"tags": {},
				},
				"before_sensitive": false,
				"after_sensitive": {
					"identity": [],
					"network_acls": [{
						"ip_rules": [false],
						"virtual_network_rules": [],
						"virtual_network_subnet_ids": [],
					}],
					"primary_access_key": true,
					"secondary_access_key": true,
					"storage": [],
					"tags": {},
				},
			},
		},
		{
			"address": "azurerm_resource_group.example",
			"mode": "managed",
			"type": "azurerm_resource_group",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"location": "westeurope",
					"name": "example-resources",
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {"id": true},
				"before_sensitive": false,
				"after_sensitive": {},
			},
		},
	],
	"configuration": {
		"provider_config": {"azurerm": {
			"name": "azurerm",
			"expressions": {"features": [{}]},
		}},
		"root_module": {"resources": [
			{
				"address": "azurerm_cognitive_account.invalid",
				"mode": "managed",
				"type": "azurerm_cognitive_account",
				"name": "invalid",
				"provider_config_key": "azurerm",
				"expressions": {
					"custom_subdomain_name": {"constant_value": "example-account-invalid"},
					"kind": {"constant_value": "Face"},
					"location": {"references": ["azurerm_resource_group.example"]},
					"name": {"constant_value": "example-account-invalid"},
					"network_acls": [{"default_action": {"constant_value": "Allow"}}],
					"resource_group_name": {"references": ["azurerm_resource_group.example"]},
					"sku_name": {"constant_value": "S0"},
					"tags": {"constant_value": {"Acceptance": "Test"}},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_cognitive_account.valid",
				"mode": "managed",
				"type": "azurerm_cognitive_account",
				"name": "valid",
				"provider_config_key": "azurerm",
				"expressions": {
					"custom_subdomain_name": {"constant_value": "example-account-valid"},
					"kind": {"constant_value": "Face"},
					"location": {"references": ["azurerm_resource_group.example"]},
					"name": {"constant_value": "example-account-valid"},
					"network_acls": [{
						"default_action": {"constant_value": "Deny"},
						"ip_rules": {"constant_value": ["10.0.0.0/16"]},
					}],
					"resource_group_name": {"references": ["azurerm_resource_group.example"]},
					"sku_name": {"constant_value": "S0"},
					"tags": {"constant_value": {"Acceptance": "Test"}},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_resource_group.example",
				"mode": "managed",
				"type": "azurerm_resource_group",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"location": {"constant_value": "West Europe"},
					"name": {"constant_value": "example-resources"},
				},
				"schema_version": 0,
			},
		]},
	},
}
