# Rego test for Functionapp HTTPS Requirement
# This rule denies functionapp resources from being created that do not require client connections to function endpoints to leverage HTTPS
package rules.functionapp_https_requirement

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

test_https_requirement {
	pol := policy with input as mock_input
	resources := {p.id: p.valid | pol[p]}

	resources["azurerm_function_app.valid"] == true
	resources["azurerm_function_app.invalid"] == false
}

# Mock input is generated plan for functionapp_https_requirement.tf
mock_plan_input = {
	"format_version": "0.2",
	"terraform_version": "1.0.11",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "azurerm_app_service_plan.example",
			"mode": "managed",
			"type": "azurerm_app_service_plan",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"app_service_environment_id": null,
				"is_xenon": null,
				"kind": "FunctionApp",
				"location": "eastus",
				"name": "azure-functions-test-service-plan",
				"per_site_scaling": null,
				"reserved": null,
				"resource_group_name": "terraform-example-resources",
				"sku": [{
					"size": "Y1",
					"tier": "Dynamic",
				}],
				"tags": null,
				"timeouts": null,
				"zone_redundant": null,
			},
			"sensitive_values": {"sku": [{}]},
		},
		{
			"address": "azurerm_function_app.invalid",
			"mode": "managed",
			"type": "azurerm_function_app",
			"name": "invalid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"client_cert_mode": null,
				"daily_memory_time_quota": null,
				"enable_builtin_logging": true,
				"enabled": true,
				"https_only": false,
				"location": "eastus",
				"name": "test-azure-functions",
				"os_type": null,
				"resource_group_name": "terraform-example-resources",
				"storage_account_name": "functionsapptestsa",
				"tags": null,
				"timeouts": null,
				"version": "~1",
			},
			"sensitive_values": {
				"app_settings": {},
				"auth_settings": [],
				"connection_string": [],
				"identity": [],
				"site_config": [],
				"site_credential": [],
				"source_control": [],
				"storage_account_access_key": true,
			},
		},
		{
			"address": "azurerm_function_app.valid",
			"mode": "managed",
			"type": "azurerm_function_app",
			"name": "valid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"client_cert_mode": null,
				"daily_memory_time_quota": null,
				"enable_builtin_logging": true,
				"enabled": true,
				"https_only": true,
				"location": "eastus",
				"name": "test-azure-functions",
				"os_type": null,
				"resource_group_name": "terraform-example-resources",
				"storage_account_name": "functionsapptestsa",
				"tags": null,
				"timeouts": null,
				"version": "~1",
			},
			"sensitive_values": {
				"app_settings": {},
				"auth_settings": [],
				"connection_string": [],
				"identity": [],
				"site_config": [],
				"site_credential": [],
				"source_control": [],
				"storage_account_access_key": true,
			},
		},
		{
			"address": "azurerm_resource_group.example",
			"mode": "managed",
			"type": "azurerm_resource_group",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"location": "eastus",
				"name": "terraform-example-resources",
				"tags": null,
				"timeouts": null,
			},
			"sensitive_values": {},
		},
		{
			"address": "azurerm_storage_account.example",
			"mode": "managed",
			"type": "azurerm_storage_account",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 2,
			"values": {
				"account_kind": "StorageV2",
				"account_replication_type": "LRS",
				"account_tier": "Standard",
				"allow_blob_public_access": false,
				"azure_files_authentication": [],
				"custom_domain": [],
				"enable_https_traffic_only": true,
				"is_hns_enabled": false,
				"location": "eastus",
				"min_tls_version": "TLS1_0",
				"name": "functionsapptestsa",
				"nfsv3_enabled": false,
				"resource_group_name": "terraform-example-resources",
				"shared_access_key_enabled": true,
				"static_website": [],
				"tags": null,
				"timeouts": null,
			},
			"sensitive_values": {
				"azure_files_authentication": [],
				"blob_properties": [],
				"custom_domain": [],
				"identity": [],
				"network_rules": [],
				"queue_properties": [],
				"routing": [],
				"share_properties": [],
				"static_website": [],
			},
		},
	]}},
	"resource_changes": [
		{
			"address": "azurerm_app_service_plan.example",
			"mode": "managed",
			"type": "azurerm_app_service_plan",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"app_service_environment_id": null,
					"is_xenon": null,
					"kind": "FunctionApp",
					"location": "eastus",
					"name": "azure-functions-test-service-plan",
					"per_site_scaling": null,
					"reserved": null,
					"resource_group_name": "terraform-example-resources",
					"sku": [{
						"size": "Y1",
						"tier": "Dynamic",
					}],
					"tags": null,
					"timeouts": null,
					"zone_redundant": null,
				},
				"after_unknown": {
					"id": true,
					"maximum_elastic_worker_count": true,
					"maximum_number_of_workers": true,
					"sku": [{"capacity": true}],
				},
				"before_sensitive": false,
				"after_sensitive": {"sku": [{}]},
			},
		},
		{
			"address": "azurerm_function_app.invalid",
			"mode": "managed",
			"type": "azurerm_function_app",
			"name": "invalid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"client_cert_mode": null,
					"daily_memory_time_quota": null,
					"enable_builtin_logging": true,
					"enabled": true,
					"https_only": false,
					"location": "eastus",
					"name": "test-azure-functions",
					"os_type": null,
					"resource_group_name": "terraform-example-resources",
					"storage_account_name": "functionsapptestsa",
					"tags": null,
					"timeouts": null,
					"version": "~1",
				},
				"after_unknown": {
					"app_service_plan_id": true,
					"app_settings": true,
					"auth_settings": true,
					"client_affinity_enabled": true,
					"connection_string": true,
					"custom_domain_verification_id": true,
					"default_hostname": true,
					"id": true,
					"identity": true,
					"key_vault_reference_identity_id": true,
					"kind": true,
					"outbound_ip_addresses": true,
					"possible_outbound_ip_addresses": true,
					"site_config": true,
					"site_credential": true,
					"source_control": true,
					"storage_account_access_key": true,
					"storage_connection_string": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"app_settings": {},
					"auth_settings": [],
					"connection_string": [],
					"identity": [],
					"site_config": [],
					"site_credential": [],
					"source_control": [],
					"storage_account_access_key": true,
					"storage_connection_string": true,
				},
			},
		},
		{
			"address": "azurerm_function_app.valid",
			"mode": "managed",
			"type": "azurerm_function_app",
			"name": "valid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"client_cert_mode": null,
					"daily_memory_time_quota": null,
					"enable_builtin_logging": true,
					"enabled": true,
					"https_only": true,
					"location": "eastus",
					"name": "test-azure-functions",
					"os_type": null,
					"resource_group_name": "terraform-example-resources",
					"storage_account_name": "functionsapptestsa",
					"tags": null,
					"timeouts": null,
					"version": "~1",
				},
				"after_unknown": {
					"app_service_plan_id": true,
					"app_settings": true,
					"auth_settings": true,
					"client_affinity_enabled": true,
					"connection_string": true,
					"custom_domain_verification_id": true,
					"default_hostname": true,
					"id": true,
					"identity": true,
					"key_vault_reference_identity_id": true,
					"kind": true,
					"outbound_ip_addresses": true,
					"possible_outbound_ip_addresses": true,
					"site_config": true,
					"site_credential": true,
					"source_control": true,
					"storage_account_access_key": true,
					"storage_connection_string": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"app_settings": {},
					"auth_settings": [],
					"connection_string": [],
					"identity": [],
					"site_config": [],
					"site_credential": [],
					"source_control": [],
					"storage_account_access_key": true,
					"storage_connection_string": true,
				},
			},
		},
		{
			"address": "azurerm_resource_group.example",
			"mode": "managed",
			"type": "azurerm_resource_group",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"location": "eastus",
					"name": "terraform-example-resources",
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {"id": true},
				"before_sensitive": false,
				"after_sensitive": {},
			},
		},
		{
			"address": "azurerm_storage_account.example",
			"mode": "managed",
			"type": "azurerm_storage_account",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"account_kind": "StorageV2",
					"account_replication_type": "LRS",
					"account_tier": "Standard",
					"allow_blob_public_access": false,
					"azure_files_authentication": [],
					"custom_domain": [],
					"enable_https_traffic_only": true,
					"is_hns_enabled": false,
					"location": "eastus",
					"min_tls_version": "TLS1_0",
					"name": "functionsapptestsa",
					"nfsv3_enabled": false,
					"resource_group_name": "terraform-example-resources",
					"shared_access_key_enabled": true,
					"static_website": [],
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {
					"access_tier": true,
					"azure_files_authentication": [],
					"blob_properties": true,
					"custom_domain": [],
					"id": true,
					"identity": true,
					"large_file_share_enabled": true,
					"network_rules": true,
					"primary_access_key": true,
					"primary_blob_connection_string": true,
					"primary_blob_endpoint": true,
					"primary_blob_host": true,
					"primary_connection_string": true,
					"primary_dfs_endpoint": true,
					"primary_dfs_host": true,
					"primary_file_endpoint": true,
					"primary_file_host": true,
					"primary_location": true,
					"primary_queue_endpoint": true,
					"primary_queue_host": true,
					"primary_table_endpoint": true,
					"primary_table_host": true,
					"primary_web_endpoint": true,
					"primary_web_host": true,
					"queue_properties": true,
					"routing": true,
					"secondary_access_key": true,
					"secondary_blob_connection_string": true,
					"secondary_blob_endpoint": true,
					"secondary_blob_host": true,
					"secondary_connection_string": true,
					"secondary_dfs_endpoint": true,
					"secondary_dfs_host": true,
					"secondary_file_endpoint": true,
					"secondary_file_host": true,
					"secondary_location": true,
					"secondary_queue_endpoint": true,
					"secondary_queue_host": true,
					"secondary_table_endpoint": true,
					"secondary_table_host": true,
					"secondary_web_endpoint": true,
					"secondary_web_host": true,
					"share_properties": true,
					"static_website": [],
				},
				"before_sensitive": false,
				"after_sensitive": {
					"azure_files_authentication": [],
					"blob_properties": [],
					"custom_domain": [],
					"identity": [],
					"network_rules": [],
					"primary_access_key": true,
					"primary_blob_connection_string": true,
					"primary_connection_string": true,
					"queue_properties": [],
					"routing": [],
					"secondary_access_key": true,
					"secondary_blob_connection_string": true,
					"secondary_connection_string": true,
					"share_properties": [],
					"static_website": [],
				},
			},
		},
	],
	"configuration": {
		"provider_config": {"azurerm": {
			"name": "azurerm",
			"version_constraint": "~> 2.0",
			"expressions": {"features": [{}]},
		}},
		"root_module": {"resources": [
			{
				"address": "azurerm_app_service_plan.example",
				"mode": "managed",
				"type": "azurerm_app_service_plan",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"kind": {"constant_value": "FunctionApp"},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "azure-functions-test-service-plan"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"sku": [{
						"size": {"constant_value": "Y1"},
						"tier": {"constant_value": "Dynamic"},
					}],
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_function_app.invalid",
				"mode": "managed",
				"type": "azurerm_function_app",
				"name": "invalid",
				"provider_config_key": "azurerm",
				"expressions": {
					"app_service_plan_id": {"references": [
						"azurerm_app_service_plan.example.id",
						"azurerm_app_service_plan.example",
					]},
					"https_only": {"constant_value": false},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "test-azure-functions"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"storage_account_access_key": {"references": [
						"azurerm_storage_account.example.primary_access_key",
						"azurerm_storage_account.example",
					]},
					"storage_account_name": {"references": [
						"azurerm_storage_account.example.name",
						"azurerm_storage_account.example",
					]},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_function_app.valid",
				"mode": "managed",
				"type": "azurerm_function_app",
				"name": "valid",
				"provider_config_key": "azurerm",
				"expressions": {
					"app_service_plan_id": {"references": [
						"azurerm_app_service_plan.example.id",
						"azurerm_app_service_plan.example",
					]},
					"https_only": {"constant_value": true},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "test-azure-functions"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"storage_account_access_key": {"references": [
						"azurerm_storage_account.example.primary_access_key",
						"azurerm_storage_account.example",
					]},
					"storage_account_name": {"references": [
						"azurerm_storage_account.example.name",
						"azurerm_storage_account.example",
					]},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_resource_group.example",
				"mode": "managed",
				"type": "azurerm_resource_group",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"location": {"constant_value": "eastus"},
					"name": {"constant_value": "terraform-example-resources"},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_storage_account.example",
				"mode": "managed",
				"type": "azurerm_storage_account",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"account_replication_type": {"constant_value": "LRS"},
					"account_tier": {"constant_value": "Standard"},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "functionsapptestsa"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
				},
				"schema_version": 2,
			},
		]},
	},
}
