# Rego test for RDS Publicly Accessible
# Validating rule rds_publicly_accessible: Deny RDS instances that are publicly accessible.
package rules.rds_publicly_accessible

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

test_rds_publicly_accessible {
	pol := policy with input as mock_input
	resources := {p.id: p.valid | pol[p]}

	resources["aws_db_instance.invalid"] == false
	resources["aws_rds_cluster_instance.valid[0]"] == true
}

# Mock input is generated plan for rds_publicly_accessible.tf
mock_plan_input = {
	"format_version": "0.1",
	"terraform_version": "0.14.9",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "aws_db_instance.invalid",
			"mode": "managed",
			"type": "aws_db_instance",
			"name": "invalid",
			"provider_name": "registry.terraform.io/hashicorp/aws",
			"schema_version": 1,
			"values": {
				"allocated_storage": 10,
				"allow_major_version_upgrade": null,
				"auto_minor_version_upgrade": true,
				"copy_tags_to_snapshot": false,
				"delete_automated_backups": true,
				"deletion_protection": null,
				"domain": null,
				"domain_iam_role_name": null,
				"enabled_cloudwatch_logs_exports": null,
				"engine": "mysql",
				"engine_version": "5.7",
				"final_snapshot_identifier": null,
				"iam_database_authentication_enabled": null,
				"instance_class": "db.t3.micro",
				"iops": null,
				"max_allocated_storage": null,
				"monitoring_interval": 0,
				"name": "mydb",
				"parameter_group_name": "default.mysql5.7",
				"password": "password",
				"performance_insights_enabled": false,
				"publicly_accessible": true,
				"replicate_source_db": null,
				"restore_to_point_in_time": [],
				"s3_import": [],
				"security_group_names": null,
				"skip_final_snapshot": true,
				"storage_encrypted": null,
				"tags": null,
				"timeouts": null,
				"username": "sql",
			},
		},
		{
			"address": "aws_rds_cluster.default",
			"mode": "managed",
			"type": "aws_rds_cluster",
			"name": "default",
			"provider_name": "registry.terraform.io/hashicorp/aws",
			"schema_version": 0,
			"values": {
				"allow_major_version_upgrade": null,
				"availability_zones": [
					"us-west-2a",
					"us-west-2b",
					"us-west-2c",
				],
				"backtrack_window": null,
				"backup_retention_period": 1,
				"cluster_identifier": "aurora-cluster-demo",
				"copy_tags_to_snapshot": false,
				"database_name": "mydb",
				"deletion_protection": null,
				"enable_http_endpoint": false,
				"enabled_cloudwatch_logs_exports": null,
				"engine": "aurora",
				"engine_mode": "provisioned",
				"final_snapshot_identifier": null,
				"global_cluster_identifier": null,
				"iam_database_authentication_enabled": null,
				"iam_roles": null,
				"master_password": "barbut8chars",
				"master_username": "foo",
				"replication_source_identifier": null,
				"restore_to_point_in_time": [],
				"s3_import": [],
				"scaling_configuration": [],
				"skip_final_snapshot": false,
				"snapshot_identifier": null,
				"source_region": null,
				"tags": null,
				"timeouts": null,
			},
		},
		{
			"address": "aws_rds_cluster_instance.valid[0]",
			"mode": "managed",
			"type": "aws_rds_cluster_instance",
			"name": "valid",
			"index": 0,
			"provider_name": "registry.terraform.io/hashicorp/aws",
			"schema_version": 0,
			"values": {
				"auto_minor_version_upgrade": true,
				"copy_tags_to_snapshot": false,
				"engine": "aurora",
				"identifier": "aurora-cluster-demo-0",
				"instance_class": "db.r4.large",
				"monitoring_interval": 0,
				"promotion_tier": 0,
				"publicly_accessible": false,
				"tags": null,
				"timeouts": null,
			},
		},
	]}},
	"resource_changes": [
		{
			"address": "aws_db_instance.invalid",
			"mode": "managed",
			"type": "aws_db_instance",
			"name": "invalid",
			"provider_name": "registry.terraform.io/hashicorp/aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"allocated_storage": 10,
					"allow_major_version_upgrade": null,
					"auto_minor_version_upgrade": true,
					"copy_tags_to_snapshot": false,
					"delete_automated_backups": true,
					"deletion_protection": null,
					"domain": null,
					"domain_iam_role_name": null,
					"enabled_cloudwatch_logs_exports": null,
					"engine": "mysql",
					"engine_version": "5.7",
					"final_snapshot_identifier": null,
					"iam_database_authentication_enabled": null,
					"instance_class": "db.t3.micro",
					"iops": null,
					"max_allocated_storage": null,
					"monitoring_interval": 0,
					"name": "mydb",
					"parameter_group_name": "default.mysql5.7",
					"password": "password",
					"performance_insights_enabled": false,
					"publicly_accessible": true,
					"replicate_source_db": null,
					"restore_to_point_in_time": [],
					"s3_import": [],
					"security_group_names": null,
					"skip_final_snapshot": true,
					"storage_encrypted": null,
					"tags": null,
					"timeouts": null,
					"username": "sql",
				},
				"after_unknown": {
					"address": true,
					"apply_immediately": true,
					"arn": true,
					"availability_zone": true,
					"backup_retention_period": true,
					"backup_window": true,
					"ca_cert_identifier": true,
					"character_set_name": true,
					"db_subnet_group_name": true,
					"endpoint": true,
					"hosted_zone_id": true,
					"id": true,
					"identifier": true,
					"identifier_prefix": true,
					"kms_key_id": true,
					"latest_restorable_time": true,
					"license_model": true,
					"maintenance_window": true,
					"monitoring_role_arn": true,
					"multi_az": true,
					"option_group_name": true,
					"performance_insights_kms_key_id": true,
					"performance_insights_retention_period": true,
					"port": true,
					"replicas": true,
					"resource_id": true,
					"restore_to_point_in_time": [],
					"s3_import": [],
					"snapshot_identifier": true,
					"status": true,
					"storage_type": true,
					"timezone": true,
					"vpc_security_group_ids": true,
				},
			},
		},
		{
			"address": "aws_rds_cluster.default",
			"mode": "managed",
			"type": "aws_rds_cluster",
			"name": "default",
			"provider_name": "registry.terraform.io/hashicorp/aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"allow_major_version_upgrade": null,
					"availability_zones": [
						"us-west-2a",
						"us-west-2b",
						"us-west-2c",
					],
					"backtrack_window": null,
					"backup_retention_period": 1,
					"cluster_identifier": "aurora-cluster-demo",
					"copy_tags_to_snapshot": false,
					"database_name": "mydb",
					"deletion_protection": null,
					"enable_http_endpoint": false,
					"enabled_cloudwatch_logs_exports": null,
					"engine": "aurora",
					"engine_mode": "provisioned",
					"final_snapshot_identifier": null,
					"global_cluster_identifier": null,
					"iam_database_authentication_enabled": null,
					"iam_roles": null,
					"master_password": "barbut8chars",
					"master_username": "foo",
					"replication_source_identifier": null,
					"restore_to_point_in_time": [],
					"s3_import": [],
					"scaling_configuration": [],
					"skip_final_snapshot": false,
					"snapshot_identifier": null,
					"source_region": null,
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {
					"apply_immediately": true,
					"arn": true,
					"availability_zones": [
						false,
						false,
						false,
					],
					"cluster_identifier_prefix": true,
					"cluster_members": true,
					"cluster_resource_id": true,
					"db_cluster_parameter_group_name": true,
					"db_subnet_group_name": true,
					"endpoint": true,
					"engine_version": true,
					"hosted_zone_id": true,
					"id": true,
					"kms_key_id": true,
					"port": true,
					"preferred_backup_window": true,
					"preferred_maintenance_window": true,
					"reader_endpoint": true,
					"restore_to_point_in_time": [],
					"s3_import": [],
					"scaling_configuration": [],
					"storage_encrypted": true,
					"vpc_security_group_ids": true,
				},
			},
		},
		{
			"address": "aws_rds_cluster_instance.valid[0]",
			"mode": "managed",
			"type": "aws_rds_cluster_instance",
			"name": "valid",
			"index": 0,
			"provider_name": "registry.terraform.io/hashicorp/aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"auto_minor_version_upgrade": true,
					"copy_tags_to_snapshot": false,
					"engine": "aurora",
					"identifier": "aurora-cluster-demo-0",
					"instance_class": "db.r4.large",
					"monitoring_interval": 0,
					"promotion_tier": 0,
					"publicly_accessible": false,
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {
					"apply_immediately": true,
					"arn": true,
					"availability_zone": true,
					"ca_cert_identifier": true,
					"cluster_identifier": true,
					"db_parameter_group_name": true,
					"db_subnet_group_name": true,
					"dbi_resource_id": true,
					"endpoint": true,
					"engine_version": true,
					"id": true,
					"identifier_prefix": true,
					"kms_key_id": true,
					"monitoring_role_arn": true,
					"performance_insights_enabled": true,
					"performance_insights_kms_key_id": true,
					"port": true,
					"preferred_backup_window": true,
					"preferred_maintenance_window": true,
					"storage_encrypted": true,
					"writer": true,
				},
			},
		},
	],
	"configuration": {
		"provider_config": {"aws": {
			"name": "aws",
			"expressions": {
				"profile": {"constant_value": "saml"},
				"region": {"constant_value": "us-east-1"},
				"shared_credentials_file": {"constant_value": "~/.aws/creds"},
			},
		}},
		"root_module": {"resources": [
			{
				"address": "aws_db_instance.invalid",
				"mode": "managed",
				"type": "aws_db_instance",
				"name": "invalid",
				"provider_config_key": "aws",
				"expressions": {
					"allocated_storage": {"constant_value": 10},
					"engine": {"constant_value": "mysql"},
					"engine_version": {"constant_value": "5.7"},
					"instance_class": {"constant_value": "db.t3.micro"},
					"name": {"constant_value": "mydb"},
					"parameter_group_name": {"constant_value": "default.mysql5.7"},
					"password": {"constant_value": "password"},
					"publicly_accessible": {"constant_value": true},
					"skip_final_snapshot": {"constant_value": true},
					"username": {"constant_value": "sql"},
				},
				"schema_version": 1,
			},
			{
				"address": "aws_rds_cluster.default",
				"mode": "managed",
				"type": "aws_rds_cluster",
				"name": "default",
				"provider_config_key": "aws",
				"expressions": {
					"availability_zones": {"constant_value": [
						"us-west-2a",
						"us-west-2b",
						"us-west-2c",
					]},
					"cluster_identifier": {"constant_value": "aurora-cluster-demo"},
					"database_name": {"constant_value": "mydb"},
					"master_password": {"constant_value": "barbut8chars"},
					"master_username": {"constant_value": "foo"},
				},
				"schema_version": 0,
			},
			{
				"address": "aws_rds_cluster_instance.valid",
				"mode": "managed",
				"type": "aws_rds_cluster_instance",
				"name": "valid",
				"provider_config_key": "aws",
				"expressions": {
					"cluster_identifier": {"references": ["aws_rds_cluster.default"]},
					"engine": {"references": ["aws_rds_cluster.default"]},
					"engine_version": {"references": ["aws_rds_cluster.default"]},
					"identifier": {"references": ["count.index"]},
					"instance_class": {"constant_value": "db.r4.large"},
					"publicly_accessible": {"constant_value": false},
				},
				"schema_version": 0,
				"count_expression": {"constant_value": 1},
			},
		]},
	},
}
