# Rego test for RDS Retention
# Validating rule rds_retention: Deny RDS instances that are not replicating data to a standby instance across AZs.
package rules.rds_retention

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

test_rds_retention {
	pol := policy with input as mock_input
	resources := {p.id: p.valid | pol[p]}

	resources["aws_db_instance.invalid-retention"] == false
	resources["aws_rds_cluster.valid-retention"] == true
}

# Mock input is generated plan for rds_retention.tf
mock_plan_input = {
	"format_version": "0.1",
	"terraform_version": "0.12.28",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "aws_db_instance.invalid-retention",
			"mode": "managed",
			"type": "aws_db_instance",
			"name": "invalid-retention",
			"provider_name": "aws",
			"schema_version": 1,
			"values": {
				"allocated_storage": 100,
				"allow_major_version_upgrade": null,
				"auto_minor_version_upgrade": false,
				"backup_retention_period": 6,
				"copy_tags_to_snapshot": false,
				"db_subnet_group_name": "db-subnetgrp",
				"delete_automated_backups": true,
				"deletion_protection": null,
				"domain": null,
				"domain_iam_role_name": null,
				"enabled_cloudwatch_logs_exports": null,
				"engine": "postgres",
				"engine_version": "11.5",
				"final_snapshot_identifier": null,
				"iam_database_authentication_enabled": null,
				"identifier": "muffy-test",
				"instance_class": "db.m5.large",
				"iops": null,
				"kms_key_id": "arn:aws:kms:us-east-1:123456789012:key/6d749788-dbdb-4e6b-ad73-eb0278614abc",
				"max_allocated_storage": null,
				"monitoring_interval": 0,
				"password": "password",
				"performance_insights_enabled": false,
				"publicly_accessible": false,
				"replicate_source_db": null,
				"s3_import": [],
				"security_group_names": null,
				"skip_final_snapshot": true,
				"snapshot_identifier": null,
				"storage_encrypted": true,
				"tags": null,
				"timeouts": null,
				"username": "postgres",
			},
		},
		{
			"address": "aws_rds_cluster.valid-retention",
			"mode": "managed",
			"type": "aws_rds_cluster",
			"name": "valid-retention",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"availability_zones": [
					"us-west-2a",
					"us-west-2b",
					"us-west-2c",
				],
				"backtrack_window": null,
				"backup_retention_period": 7,
				"cluster_identifier": "aurora-cluster-demo",
				"copy_tags_to_snapshot": false,
				"database_name": "mydb",
				"deletion_protection": null,
				"enable_http_endpoint": false,
				"enabled_cloudwatch_logs_exports": null,
				"engine": "aurora-mysql",
				"engine_mode": "provisioned",
				"engine_version": "5.7.mysql_aurora.2.03.2",
				"final_snapshot_identifier": null,
				"global_cluster_identifier": null,
				"iam_database_authentication_enabled": null,
				"iam_roles": null,
				"master_password": "bar",
				"master_username": "foo",
				"preferred_backup_window": "07:00-09:00",
				"replication_source_identifier": null,
				"s3_import": [],
				"scaling_configuration": [],
				"skip_final_snapshot": false,
				"snapshot_identifier": null,
				"source_region": null,
				"storage_encrypted": true,
				"tags": null,
				"timeouts": null,
			},
		},
	]}},
	"resource_changes": [
		{
			"address": "aws_db_instance.invalid-retention",
			"mode": "managed",
			"type": "aws_db_instance",
			"name": "invalid-retention",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"allocated_storage": 100,
					"allow_major_version_upgrade": null,
					"auto_minor_version_upgrade": false,
					"backup_retention_period": 6,
					"copy_tags_to_snapshot": false,
					"db_subnet_group_name": "db-subnetgrp",
					"delete_automated_backups": true,
					"deletion_protection": null,
					"domain": null,
					"domain_iam_role_name": null,
					"enabled_cloudwatch_logs_exports": null,
					"engine": "postgres",
					"engine_version": "11.5",
					"final_snapshot_identifier": null,
					"iam_database_authentication_enabled": null,
					"identifier": "muffy-test",
					"instance_class": "db.m5.large",
					"iops": null,
					"kms_key_id": "arn:aws:kms:us-east-1:123456789012:key/6d749788-dbdb-4e6b-ad73-eb0278614abc",
					"max_allocated_storage": null,
					"monitoring_interval": 0,
					"password": "password",
					"performance_insights_enabled": false,
					"publicly_accessible": false,
					"replicate_source_db": null,
					"s3_import": [],
					"security_group_names": null,
					"skip_final_snapshot": true,
					"snapshot_identifier": null,
					"storage_encrypted": true,
					"tags": null,
					"timeouts": null,
					"username": "postgres",
				},
				"after_unknown": {
					"address": true,
					"apply_immediately": true,
					"arn": true,
					"availability_zone": true,
					"backup_window": true,
					"ca_cert_identifier": true,
					"character_set_name": true,
					"endpoint": true,
					"hosted_zone_id": true,
					"id": true,
					"identifier_prefix": true,
					"license_model": true,
					"maintenance_window": true,
					"monitoring_role_arn": true,
					"multi_az": true,
					"name": true,
					"option_group_name": true,
					"parameter_group_name": true,
					"performance_insights_kms_key_id": true,
					"performance_insights_retention_period": true,
					"port": true,
					"replicas": true,
					"resource_id": true,
					"s3_import": [],
					"status": true,
					"storage_type": true,
					"timezone": true,
					"vpc_security_group_ids": true,
				},
			},
		},
		{
			"address": "aws_rds_cluster.valid-retention",
			"mode": "managed",
			"type": "aws_rds_cluster",
			"name": "valid-retention",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"availability_zones": [
						"us-west-2a",
						"us-west-2b",
						"us-west-2c",
					],
					"backtrack_window": null,
					"backup_retention_period": 7,
					"cluster_identifier": "aurora-cluster-demo",
					"copy_tags_to_snapshot": false,
					"database_name": "mydb",
					"deletion_protection": null,
					"enable_http_endpoint": false,
					"enabled_cloudwatch_logs_exports": null,
					"engine": "aurora-mysql",
					"engine_mode": "provisioned",
					"engine_version": "5.7.mysql_aurora.2.03.2",
					"final_snapshot_identifier": null,
					"global_cluster_identifier": null,
					"iam_database_authentication_enabled": null,
					"iam_roles": null,
					"master_password": "bar",
					"master_username": "foo",
					"preferred_backup_window": "07:00-09:00",
					"replication_source_identifier": null,
					"s3_import": [],
					"scaling_configuration": [],
					"skip_final_snapshot": false,
					"snapshot_identifier": null,
					"source_region": null,
					"storage_encrypted": true,
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {
					"apply_immediately": true,
					"arn": true,
					"availability_zones": [
						false,
						false,
						false,
					],
					"cluster_identifier_prefix": true,
					"cluster_members": true,
					"cluster_resource_id": true,
					"db_cluster_parameter_group_name": true,
					"db_subnet_group_name": true,
					"endpoint": true,
					"hosted_zone_id": true,
					"id": true,
					"kms_key_id": true,
					"port": true,
					"preferred_maintenance_window": true,
					"reader_endpoint": true,
					"s3_import": [],
					"scaling_configuration": [],
					"vpc_security_group_ids": true,
				},
			},
		},
	],
	"configuration": {
		"provider_config": {"aws": {
			"name": "aws",
			"expressions": {
				"profile": {"constant_value": "saml"},
				"region": {"constant_value": "us-east-1"},
				"shared_credentials_file": {"constant_value": "~/.aws/creds"},
			},
		}},
		"root_module": {"resources": [
			{
				"address": "aws_db_instance.invalid-retention",
				"mode": "managed",
				"type": "aws_db_instance",
				"name": "invalid-retention",
				"provider_config_key": "aws",
				"expressions": {
					"allocated_storage": {"constant_value": 100},
					"auto_minor_version_upgrade": {"constant_value": false},
					"backup_retention_period": {"constant_value": 6},
					"db_subnet_group_name": {"constant_value": "db-subnetgrp"},
					"engine": {"constant_value": "postgres"},
					"engine_version": {"constant_value": "11.5"},
					"identifier": {"constant_value": "muffy-test"},
					"instance_class": {"constant_value": "db.m5.large"},
					"kms_key_id": {"constant_value": "arn:aws:kms:us-east-1:123456789012:key/6d749788-dbdb-4e6b-ad73-eb0278614abc"},
					"password": {"constant_value": "password"},
					"skip_final_snapshot": {"constant_value": true},
					"storage_encrypted": {"constant_value": true},
					"username": {"constant_value": "postgres"},
				},
				"schema_version": 1,
			},
			{
				"address": "aws_rds_cluster.valid-retention",
				"mode": "managed",
				"type": "aws_rds_cluster",
				"name": "valid-retention",
				"provider_config_key": "aws",
				"expressions": {
					"availability_zones": {"constant_value": [
						"us-west-2a",
						"us-west-2b",
						"us-west-2c",
					]},
					"backup_retention_period": {"constant_value": 7},
					"cluster_identifier": {"constant_value": "aurora-cluster-demo"},
					"database_name": {"constant_value": "mydb"},
					"engine": {"constant_value": "aurora-mysql"},
					"engine_version": {"constant_value": "5.7.mysql_aurora.2.03.2"},
					"master_password": {"constant_value": "bar"},
					"master_username": {"constant_value": "foo"},
					"preferred_backup_window": {"constant_value": "07:00-09:00"},
					"storage_encrypted": {"constant_value": true},
				},
				"schema_version": 0,
			},
		]},
	},
}
