# Rego test for Virtual Machine SKU Limits
# Validating rule virtual_machine_sku_limits.rego: Deny VM resources that use a restricted SKU (instance size)
package rules.virtual_machine_sku_limits

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

test_nat_gateway {
	pol := policy with input as mock_input
	resources := {p.id: p.valid | pol[p]}

	# Windows VMs
	resources["azurerm_windows_virtual_machine.bad_vm_size_example"] == false
	resources["azurerm_windows_virtual_machine.valid_vm_size_example"] == true

	# Linux VMs
	resources["azurerm_linux_virtual_machine.bad_vm_size_example"] == false
	resources["azurerm_linux_virtual_machine.valid_vm_size_example"] == true
}

# Mock input is generated plan for virtual_machine_sku_limits.tf
mock_plan_input = {
	"format_version": "0.2",
	"terraform_version": "1.0.3",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "azurerm_linux_virtual_machine.bad_vm_size_example",
			"mode": "managed",
			"type": "azurerm_linux_virtual_machine",
			"name": "bad_vm_size_example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"additional_capabilities": [],
				"admin_password": null,
				"admin_ssh_key": [],
				"admin_username": "adminuser",
				"allow_extension_operations": true,
				"availability_set_id": null,
				"boot_diagnostics": [],
				"custom_data": null,
				"dedicated_host_id": null,
				"disable_password_authentication": true,
				"encryption_at_host_enabled": null,
				"eviction_policy": null,
				"extensions_time_budget": "PT1H30M",
				"identity": [],
				"license_type": null,
				"location": "eastus",
				"max_bid_price": -1,
				"name": "example-machine",
				"os_disk": [{
					"caching": "ReadWrite",
					"diff_disk_settings": [],
					"disk_encryption_set_id": null,
					"storage_account_type": "Standard_LRS",
					"write_accelerator_enabled": false,
				}],
				"patch_mode": null,
				"plan": [],
				"platform_fault_domain": -1,
				"priority": "Regular",
				"provision_vm_agent": true,
				"proximity_placement_group_id": null,
				"resource_group_name": "terraform-example-resources",
				"secret": [],
				"size": "Standard_FX48mds",
				"source_image_id": null,
				"source_image_reference": [{
					"offer": "UbuntuServer",
					"publisher": "Canonical",
					"sku": "16.04-LTS",
					"version": "latest",
				}],
				"tags": {"Exception": "DenyGoldenImage"},
				"timeouts": null,
				"virtual_machine_scale_set_id": null,
			},
			"sensitive_values": {
				"additional_capabilities": [],
				"admin_ssh_key": [],
				"boot_diagnostics": [],
				"identity": [],
				"network_interface_ids": [],
				"os_disk": [{"diff_disk_settings": []}],
				"plan": [],
				"private_ip_addresses": [],
				"public_ip_addresses": [],
				"secret": [],
				"source_image_reference": [{}],
				"tags": {},
			},
		},
		{
			"address": "azurerm_linux_virtual_machine.valid_vm_size_example",
			"mode": "managed",
			"type": "azurerm_linux_virtual_machine",
			"name": "valid_vm_size_example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"additional_capabilities": [],
				"admin_password": null,
				"admin_ssh_key": [],
				"admin_username": "adminuser",
				"allow_extension_operations": true,
				"availability_set_id": null,
				"boot_diagnostics": [],
				"custom_data": null,
				"dedicated_host_id": null,
				"disable_password_authentication": true,
				"encryption_at_host_enabled": null,
				"eviction_policy": null,
				"extensions_time_budget": "PT1H30M",
				"identity": [],
				"license_type": null,
				"location": "eastus",
				"max_bid_price": -1,
				"name": "example-machine",
				"os_disk": [{
					"caching": "ReadWrite",
					"diff_disk_settings": [],
					"disk_encryption_set_id": null,
					"storage_account_type": "Standard_LRS",
					"write_accelerator_enabled": false,
				}],
				"patch_mode": null,
				"plan": [],
				"platform_fault_domain": -1,
				"priority": "Regular",
				"provision_vm_agent": true,
				"proximity_placement_group_id": null,
				"resource_group_name": "terraform-example-resources",
				"secret": [],
				"size": "Standard_D4_v4",
				"source_image_id": null,
				"source_image_reference": [{
					"offer": "UbuntuServer",
					"publisher": "Canonical",
					"sku": "16.04-LTS",
					"version": "latest",
				}],
				"tags": {"Exception": "DenyGoldenImage"},
				"timeouts": null,
				"virtual_machine_scale_set_id": null,
			},
			"sensitive_values": {
				"additional_capabilities": [],
				"admin_ssh_key": [],
				"boot_diagnostics": [],
				"identity": [],
				"network_interface_ids": [],
				"os_disk": [{"diff_disk_settings": []}],
				"plan": [],
				"private_ip_addresses": [],
				"public_ip_addresses": [],
				"secret": [],
				"source_image_reference": [{}],
				"tags": {},
			},
		},
		{
			"address": "azurerm_network_interface.example",
			"mode": "managed",
			"type": "azurerm_network_interface",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"enable_accelerated_networking": false,
				"enable_ip_forwarding": false,
				"ip_configuration": [{
					"name": "internal",
					"private_ip_address_allocation": "dynamic",
					"private_ip_address_version": "IPv4",
					"public_ip_address_id": null,
				}],
				"location": "eastus",
				"name": "example-nic",
				"resource_group_name": "terraform-example-resources",
				"tags": null,
				"timeouts": null,
			},
			"sensitive_values": {
				"applied_dns_servers": [],
				"dns_servers": [],
				"ip_configuration": [{}],
				"private_ip_addresses": [],
			},
		},
		{
			"address": "azurerm_resource_group.example",
			"mode": "managed",
			"type": "azurerm_resource_group",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"location": "eastus",
				"name": "terraform-example-resources",
				"tags": null,
				"timeouts": null,
			},
			"sensitive_values": {},
		},
		{
			"address": "azurerm_subnet.example",
			"mode": "managed",
			"type": "azurerm_subnet",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"address_prefixes": ["10.0.2.0/24"],
				"delegation": [],
				"enforce_private_link_endpoint_network_policies": false,
				"enforce_private_link_service_network_policies": false,
				"name": "internal",
				"resource_group_name": "terraform-example-resources",
				"service_endpoint_policy_ids": null,
				"service_endpoints": null,
				"timeouts": null,
				"virtual_network_name": "example-network",
			},
			"sensitive_values": {
				"address_prefixes": [false],
				"delegation": [],
			},
		},
		{
			"address": "azurerm_virtual_network.example",
			"mode": "managed",
			"type": "azurerm_virtual_network",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"address_space": ["10.0.0.0/16"],
				"bgp_community": null,
				"ddos_protection_plan": [],
				"location": "eastus",
				"name": "example-network",
				"resource_group_name": "terraform-example-resources",
				"tags": null,
				"timeouts": null,
				"vm_protection_enabled": false,
			},
			"sensitive_values": {
				"address_space": [false],
				"ddos_protection_plan": [],
				"dns_servers": [],
				"subnet": [],
			},
		},
		{
			"address": "azurerm_windows_virtual_machine.bad_vm_size_example",
			"mode": "managed",
			"type": "azurerm_windows_virtual_machine",
			"name": "bad_vm_size_example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"additional_capabilities": [],
				"additional_unattend_content": [],
				"admin_password": "P@$$w0rd1234!",
				"admin_username": "adminuser",
				"allow_extension_operations": true,
				"availability_set_id": null,
				"boot_diagnostics": [],
				"custom_data": null,
				"dedicated_host_id": null,
				"enable_automatic_updates": true,
				"encryption_at_host_enabled": null,
				"eviction_policy": null,
				"extensions_time_budget": "PT1H30M",
				"identity": [],
				"license_type": null,
				"location": "eastus",
				"max_bid_price": -1,
				"name": "example-machine",
				"os_disk": [{
					"caching": "ReadWrite",
					"diff_disk_settings": [],
					"disk_encryption_set_id": null,
					"storage_account_type": "Standard_LRS",
					"write_accelerator_enabled": false,
				}],
				"patch_mode": "AutomaticByOS",
				"plan": [],
				"platform_fault_domain": -1,
				"priority": "Regular",
				"provision_vm_agent": true,
				"proximity_placement_group_id": null,
				"resource_group_name": "terraform-example-resources",
				"secret": [],
				"size": "Standard_FX48mds",
				"source_image_id": null,
				"source_image_reference": [{
					"offer": "WindowsServer",
					"publisher": "MicrosoftWindowsServer",
					"sku": "2016-Datacenter",
					"version": "latest",
				}],
				"tags": {"Exception": "DenyGoldenImage"},
				"timeouts": null,
				"timezone": null,
				"virtual_machine_scale_set_id": null,
				"winrm_listener": [],
			},
			"sensitive_values": {
				"additional_capabilities": [],
				"additional_unattend_content": [],
				"boot_diagnostics": [],
				"identity": [],
				"network_interface_ids": [],
				"os_disk": [{"diff_disk_settings": []}],
				"plan": [],
				"private_ip_addresses": [],
				"public_ip_addresses": [],
				"secret": [],
				"source_image_reference": [{}],
				"tags": {},
				"winrm_listener": [],
			},
		},
		{
			"address": "azurerm_windows_virtual_machine.valid_vm_size_example",
			"mode": "managed",
			"type": "azurerm_windows_virtual_machine",
			"name": "valid_vm_size_example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"additional_capabilities": [],
				"additional_unattend_content": [],
				"admin_password": "P@$$w0rd1234!",
				"admin_username": "adminuser",
				"allow_extension_operations": true,
				"availability_set_id": null,
				"boot_diagnostics": [],
				"custom_data": null,
				"dedicated_host_id": null,
				"enable_automatic_updates": true,
				"encryption_at_host_enabled": null,
				"eviction_policy": null,
				"extensions_time_budget": "PT1H30M",
				"identity": [],
				"license_type": null,
				"location": "eastus",
				"max_bid_price": -1,
				"name": "example-machine",
				"os_disk": [{
					"caching": "ReadWrite",
					"diff_disk_settings": [],
					"disk_encryption_set_id": null,
					"storage_account_type": "Standard_LRS",
					"write_accelerator_enabled": false,
				}],
				"patch_mode": "AutomaticByOS",
				"plan": [],
				"platform_fault_domain": -1,
				"priority": "Regular",
				"provision_vm_agent": true,
				"proximity_placement_group_id": null,
				"resource_group_name": "terraform-example-resources",
				"secret": [],
				"size": "Standard_D4_v4",
				"source_image_id": null,
				"source_image_reference": [{
					"offer": "WindowsServer",
					"publisher": "MicrosoftWindowsServer",
					"sku": "2016-Datacenter",
					"version": "latest",
				}],
				"tags": {"Exception": "DenyGoldenImage"},
				"timeouts": null,
				"timezone": null,
				"virtual_machine_scale_set_id": null,
				"winrm_listener": [],
			},
			"sensitive_values": {
				"additional_capabilities": [],
				"additional_unattend_content": [],
				"boot_diagnostics": [],
				"identity": [],
				"network_interface_ids": [],
				"os_disk": [{"diff_disk_settings": []}],
				"plan": [],
				"private_ip_addresses": [],
				"public_ip_addresses": [],
				"secret": [],
				"source_image_reference": [{}],
				"tags": {},
				"winrm_listener": [],
			},
		},
	]}},
	"resource_changes": [
		{
			"address": "azurerm_linux_virtual_machine.bad_vm_size_example",
			"mode": "managed",
			"type": "azurerm_linux_virtual_machine",
			"name": "bad_vm_size_example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"additional_capabilities": [],
					"admin_password": null,
					"admin_ssh_key": [],
					"admin_username": "adminuser",
					"allow_extension_operations": true,
					"availability_set_id": null,
					"boot_diagnostics": [],
					"custom_data": null,
					"dedicated_host_id": null,
					"disable_password_authentication": true,
					"encryption_at_host_enabled": null,
					"eviction_policy": null,
					"extensions_time_budget": "PT1H30M",
					"identity": [],
					"license_type": null,
					"location": "eastus",
					"max_bid_price": -1,
					"name": "example-machine",
					"os_disk": [{
						"caching": "ReadWrite",
						"diff_disk_settings": [],
						"disk_encryption_set_id": null,
						"storage_account_type": "Standard_LRS",
						"write_accelerator_enabled": false,
					}],
					"patch_mode": null,
					"plan": [],
					"platform_fault_domain": -1,
					"priority": "Regular",
					"provision_vm_agent": true,
					"proximity_placement_group_id": null,
					"resource_group_name": "terraform-example-resources",
					"secret": [],
					"size": "Standard_FX48mds",
					"source_image_id": null,
					"source_image_reference": [{
						"offer": "UbuntuServer",
						"publisher": "Canonical",
						"sku": "16.04-LTS",
						"version": "latest",
					}],
					"tags": {"Exception": "DenyGoldenImage"},
					"timeouts": null,
					"virtual_machine_scale_set_id": null,
				},
				"after_unknown": {
					"additional_capabilities": [],
					"admin_ssh_key": [],
					"boot_diagnostics": [],
					"computer_name": true,
					"id": true,
					"identity": [],
					"network_interface_ids": true,
					"os_disk": [{
						"diff_disk_settings": [],
						"disk_size_gb": true,
						"name": true,
					}],
					"plan": [],
					"private_ip_address": true,
					"private_ip_addresses": true,
					"public_ip_address": true,
					"public_ip_addresses": true,
					"secret": [],
					"source_image_reference": [{}],
					"tags": {},
					"virtual_machine_id": true,
					"zone": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"additional_capabilities": [],
					"admin_password": true,
					"admin_ssh_key": [],
					"boot_diagnostics": [],
					"custom_data": true,
					"identity": [],
					"network_interface_ids": [],
					"os_disk": [{"diff_disk_settings": []}],
					"plan": [],
					"private_ip_addresses": [],
					"public_ip_addresses": [],
					"secret": [],
					"source_image_reference": [{}],
					"tags": {},
				},
			},
		},
		{
			"address": "azurerm_linux_virtual_machine.valid_vm_size_example",
			"mode": "managed",
			"type": "azurerm_linux_virtual_machine",
			"name": "valid_vm_size_example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"additional_capabilities": [],
					"admin_password": null,
					"admin_ssh_key": [],
					"admin_username": "adminuser",
					"allow_extension_operations": true,
					"availability_set_id": null,
					"boot_diagnostics": [],
					"custom_data": null,
					"dedicated_host_id": null,
					"disable_password_authentication": true,
					"encryption_at_host_enabled": null,
					"eviction_policy": null,
					"extensions_time_budget": "PT1H30M",
					"identity": [],
					"license_type": null,
					"location": "eastus",
					"max_bid_price": -1,
					"name": "example-machine",
					"os_disk": [{
						"caching": "ReadWrite",
						"diff_disk_settings": [],
						"disk_encryption_set_id": null,
						"storage_account_type": "Standard_LRS",
						"write_accelerator_enabled": false,
					}],
					"patch_mode": null,
					"plan": [],
					"platform_fault_domain": -1,
					"priority": "Regular",
					"provision_vm_agent": true,
					"proximity_placement_group_id": null,
					"resource_group_name": "terraform-example-resources",
					"secret": [],
					"size": "Standard_D4_v4",
					"source_image_id": null,
					"source_image_reference": [{
						"offer": "UbuntuServer",
						"publisher": "Canonical",
						"sku": "16.04-LTS",
						"version": "latest",
					}],
					"tags": {"Exception": "DenyGoldenImage"},
					"timeouts": null,
					"virtual_machine_scale_set_id": null,
				},
				"after_unknown": {
					"additional_capabilities": [],
					"admin_ssh_key": [],
					"boot_diagnostics": [],
					"computer_name": true,
					"id": true,
					"identity": [],
					"network_interface_ids": true,
					"os_disk": [{
						"diff_disk_settings": [],
						"disk_size_gb": true,
						"name": true,
					}],
					"plan": [],
					"private_ip_address": true,
					"private_ip_addresses": true,
					"public_ip_address": true,
					"public_ip_addresses": true,
					"secret": [],
					"source_image_reference": [{}],
					"tags": {},
					"virtual_machine_id": true,
					"zone": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"additional_capabilities": [],
					"admin_password": true,
					"admin_ssh_key": [],
					"boot_diagnostics": [],
					"custom_data": true,
					"identity": [],
					"network_interface_ids": [],
					"os_disk": [{"diff_disk_settings": []}],
					"plan": [],
					"private_ip_addresses": [],
					"public_ip_addresses": [],
					"secret": [],
					"source_image_reference": [{}],
					"tags": {},
				},
			},
		},
		{
			"address": "azurerm_network_interface.example",
			"mode": "managed",
			"type": "azurerm_network_interface",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"enable_accelerated_networking": false,
					"enable_ip_forwarding": false,
					"ip_configuration": [{
						"name": "internal",
						"private_ip_address_allocation": "dynamic",
						"private_ip_address_version": "IPv4",
						"public_ip_address_id": null,
					}],
					"location": "eastus",
					"name": "example-nic",
					"resource_group_name": "terraform-example-resources",
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {
					"applied_dns_servers": true,
					"dns_servers": true,
					"id": true,
					"internal_dns_name_label": true,
					"internal_domain_name_suffix": true,
					"ip_configuration": [{
						"gateway_load_balancer_frontend_ip_configuration_id": true,
						"primary": true,
						"private_ip_address": true,
						"subnet_id": true,
					}],
					"mac_address": true,
					"private_ip_address": true,
					"private_ip_addresses": true,
					"virtual_machine_id": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"applied_dns_servers": [],
					"dns_servers": [],
					"ip_configuration": [{}],
					"private_ip_addresses": [],
				},
			},
		},
		{
			"address": "azurerm_resource_group.example",
			"mode": "managed",
			"type": "azurerm_resource_group",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"location": "eastus",
					"name": "terraform-example-resources",
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {"id": true},
				"before_sensitive": false,
				"after_sensitive": {},
			},
		},
		{
			"address": "azurerm_subnet.example",
			"mode": "managed",
			"type": "azurerm_subnet",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"address_prefixes": ["10.0.2.0/24"],
					"delegation": [],
					"enforce_private_link_endpoint_network_policies": false,
					"enforce_private_link_service_network_policies": false,
					"name": "internal",
					"resource_group_name": "terraform-example-resources",
					"service_endpoint_policy_ids": null,
					"service_endpoints": null,
					"timeouts": null,
					"virtual_network_name": "example-network",
				},
				"after_unknown": {
					"address_prefix": true,
					"address_prefixes": [false],
					"delegation": [],
					"id": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"address_prefixes": [false],
					"delegation": [],
				},
			},
		},
		{
			"address": "azurerm_virtual_network.example",
			"mode": "managed",
			"type": "azurerm_virtual_network",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"address_space": ["10.0.0.0/16"],
					"bgp_community": null,
					"ddos_protection_plan": [],
					"location": "eastus",
					"name": "example-network",
					"resource_group_name": "terraform-example-resources",
					"tags": null,
					"timeouts": null,
					"vm_protection_enabled": false,
				},
				"after_unknown": {
					"address_space": [false],
					"ddos_protection_plan": [],
					"dns_servers": true,
					"guid": true,
					"id": true,
					"subnet": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"address_space": [false],
					"ddos_protection_plan": [],
					"dns_servers": [],
					"subnet": [],
				},
			},
		},
		{
			"address": "azurerm_windows_virtual_machine.bad_vm_size_example",
			"mode": "managed",
			"type": "azurerm_windows_virtual_machine",
			"name": "bad_vm_size_example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"additional_capabilities": [],
					"additional_unattend_content": [],
					"admin_password": "P@$$w0rd1234!",
					"admin_username": "adminuser",
					"allow_extension_operations": true,
					"availability_set_id": null,
					"boot_diagnostics": [],
					"custom_data": null,
					"dedicated_host_id": null,
					"enable_automatic_updates": true,
					"encryption_at_host_enabled": null,
					"eviction_policy": null,
					"extensions_time_budget": "PT1H30M",
					"identity": [],
					"license_type": null,
					"location": "eastus",
					"max_bid_price": -1,
					"name": "example-machine",
					"os_disk": [{
						"caching": "ReadWrite",
						"diff_disk_settings": [],
						"disk_encryption_set_id": null,
						"storage_account_type": "Standard_LRS",
						"write_accelerator_enabled": false,
					}],
					"patch_mode": "AutomaticByOS",
					"plan": [],
					"platform_fault_domain": -1,
					"priority": "Regular",
					"provision_vm_agent": true,
					"proximity_placement_group_id": null,
					"resource_group_name": "terraform-example-resources",
					"secret": [],
					"size": "Standard_FX48mds",
					"source_image_id": null,
					"source_image_reference": [{
						"offer": "WindowsServer",
						"publisher": "MicrosoftWindowsServer",
						"sku": "2016-Datacenter",
						"version": "latest",
					}],
					"tags": {"Exception": "DenyGoldenImage"},
					"timeouts": null,
					"timezone": null,
					"virtual_machine_scale_set_id": null,
					"winrm_listener": [],
				},
				"after_unknown": {
					"additional_capabilities": [],
					"additional_unattend_content": [],
					"boot_diagnostics": [],
					"computer_name": true,
					"id": true,
					"identity": [],
					"network_interface_ids": true,
					"os_disk": [{
						"diff_disk_settings": [],
						"disk_size_gb": true,
						"name": true,
					}],
					"plan": [],
					"private_ip_address": true,
					"private_ip_addresses": true,
					"public_ip_address": true,
					"public_ip_addresses": true,
					"secret": [],
					"source_image_reference": [{}],
					"tags": {},
					"virtual_machine_id": true,
					"winrm_listener": [],
					"zone": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"additional_capabilities": [],
					"additional_unattend_content": [],
					"admin_password": true,
					"boot_diagnostics": [],
					"custom_data": true,
					"identity": [],
					"network_interface_ids": [],
					"os_disk": [{"diff_disk_settings": []}],
					"plan": [],
					"private_ip_addresses": [],
					"public_ip_addresses": [],
					"secret": [],
					"source_image_reference": [{}],
					"tags": {},
					"winrm_listener": [],
				},
			},
		},
		{
			"address": "azurerm_windows_virtual_machine.valid_vm_size_example",
			"mode": "managed",
			"type": "azurerm_windows_virtual_machine",
			"name": "valid_vm_size_example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"additional_capabilities": [],
					"additional_unattend_content": [],
					"admin_password": "P@$$w0rd1234!",
					"admin_username": "adminuser",
					"allow_extension_operations": true,
					"availability_set_id": null,
					"boot_diagnostics": [],
					"custom_data": null,
					"dedicated_host_id": null,
					"enable_automatic_updates": true,
					"encryption_at_host_enabled": null,
					"eviction_policy": null,
					"extensions_time_budget": "PT1H30M",
					"identity": [],
					"license_type": null,
					"location": "eastus",
					"max_bid_price": -1,
					"name": "example-machine",
					"os_disk": [{
						"caching": "ReadWrite",
						"diff_disk_settings": [],
						"disk_encryption_set_id": null,
						"storage_account_type": "Standard_LRS",
						"write_accelerator_enabled": false,
					}],
					"patch_mode": "AutomaticByOS",
					"plan": [],
					"platform_fault_domain": -1,
					"priority": "Regular",
					"provision_vm_agent": true,
					"proximity_placement_group_id": null,
					"resource_group_name": "terraform-example-resources",
					"secret": [],
					"size": "Standard_D4_v4",
					"source_image_id": null,
					"source_image_reference": [{
						"offer": "WindowsServer",
						"publisher": "MicrosoftWindowsServer",
						"sku": "2016-Datacenter",
						"version": "latest",
					}],
					"tags": {"Exception": "DenyGoldenImage"},
					"timeouts": null,
					"timezone": null,
					"virtual_machine_scale_set_id": null,
					"winrm_listener": [],
				},
				"after_unknown": {
					"additional_capabilities": [],
					"additional_unattend_content": [],
					"boot_diagnostics": [],
					"computer_name": true,
					"id": true,
					"identity": [],
					"network_interface_ids": true,
					"os_disk": [{
						"diff_disk_settings": [],
						"disk_size_gb": true,
						"name": true,
					}],
					"plan": [],
					"private_ip_address": true,
					"private_ip_addresses": true,
					"public_ip_address": true,
					"public_ip_addresses": true,
					"secret": [],
					"source_image_reference": [{}],
					"tags": {},
					"virtual_machine_id": true,
					"winrm_listener": [],
					"zone": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"additional_capabilities": [],
					"additional_unattend_content": [],
					"admin_password": true,
					"boot_diagnostics": [],
					"custom_data": true,
					"identity": [],
					"network_interface_ids": [],
					"os_disk": [{"diff_disk_settings": []}],
					"plan": [],
					"private_ip_addresses": [],
					"public_ip_addresses": [],
					"secret": [],
					"source_image_reference": [{}],
					"tags": {},
					"winrm_listener": [],
				},
			},
		},
	],
	"configuration": {
		"provider_config": {"azurerm": {
			"name": "azurerm",
			"version_constraint": "~> 2.0",
			"expressions": {"features": [{}]},
		}},
		"root_module": {"resources": [
			{
				"address": "azurerm_linux_virtual_machine.bad_vm_size_example",
				"mode": "managed",
				"type": "azurerm_linux_virtual_machine",
				"name": "bad_vm_size_example",
				"provider_config_key": "azurerm",
				"expressions": {
					"admin_username": {"constant_value": "adminuser"},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "example-machine"},
					"network_interface_ids": {"references": [
						"azurerm_network_interface.example.id",
						"azurerm_network_interface.example",
					]},
					"os_disk": [{
						"caching": {"constant_value": "ReadWrite"},
						"storage_account_type": {"constant_value": "Standard_LRS"},
					}],
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"size": {"constant_value": "Standard_FX48mds"},
					"source_image_reference": [{
						"offer": {"constant_value": "UbuntuServer"},
						"publisher": {"constant_value": "Canonical"},
						"sku": {"constant_value": "16.04-LTS"},
						"version": {"constant_value": "latest"},
					}],
					"tags": {"constant_value": {"Exception": "DenyGoldenImage"}},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_linux_virtual_machine.valid_vm_size_example",
				"mode": "managed",
				"type": "azurerm_linux_virtual_machine",
				"name": "valid_vm_size_example",
				"provider_config_key": "azurerm",
				"expressions": {
					"admin_username": {"constant_value": "adminuser"},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "example-machine"},
					"network_interface_ids": {"references": [
						"azurerm_network_interface.example.id",
						"azurerm_network_interface.example",
					]},
					"os_disk": [{
						"caching": {"constant_value": "ReadWrite"},
						"storage_account_type": {"constant_value": "Standard_LRS"},
					}],
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"size": {"constant_value": "Standard_D4_v4"},
					"source_image_reference": [{
						"offer": {"constant_value": "UbuntuServer"},
						"publisher": {"constant_value": "Canonical"},
						"sku": {"constant_value": "16.04-LTS"},
						"version": {"constant_value": "latest"},
					}],
					"tags": {"constant_value": {"Exception": "DenyGoldenImage"}},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_network_interface.example",
				"mode": "managed",
				"type": "azurerm_network_interface",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"ip_configuration": [{
						"name": {"constant_value": "internal"},
						"private_ip_address_allocation": {"constant_value": "Dynamic"},
						"subnet_id": {"references": [
							"azurerm_subnet.example.id",
							"azurerm_subnet.example",
						]},
					}],
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "example-nic"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_resource_group.example",
				"mode": "managed",
				"type": "azurerm_resource_group",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"location": {"constant_value": "eastus"},
					"name": {"constant_value": "terraform-example-resources"},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_subnet.example",
				"mode": "managed",
				"type": "azurerm_subnet",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"address_prefixes": {"constant_value": ["10.0.2.0/24"]},
					"name": {"constant_value": "internal"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"virtual_network_name": {"references": [
						"azurerm_virtual_network.example.name",
						"azurerm_virtual_network.example",
					]},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_virtual_network.example",
				"mode": "managed",
				"type": "azurerm_virtual_network",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"address_space": {"constant_value": ["10.0.0.0/16"]},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "example-network"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_windows_virtual_machine.bad_vm_size_example",
				"mode": "managed",
				"type": "azurerm_windows_virtual_machine",
				"name": "bad_vm_size_example",
				"provider_config_key": "azurerm",
				"expressions": {
					"admin_password": {"constant_value": "P@$$w0rd1234!"},
					"admin_username": {"constant_value": "adminuser"},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "example-machine"},
					"network_interface_ids": {"references": [
						"azurerm_network_interface.example.id",
						"azurerm_network_interface.example",
					]},
					"os_disk": [{
						"caching": {"constant_value": "ReadWrite"},
						"storage_account_type": {"constant_value": "Standard_LRS"},
					}],
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"size": {"constant_value": "Standard_FX48mds"},
					"source_image_reference": [{
						"offer": {"constant_value": "WindowsServer"},
						"publisher": {"constant_value": "MicrosoftWindowsServer"},
						"sku": {"constant_value": "2016-Datacenter"},
						"version": {"constant_value": "latest"},
					}],
					"tags": {"constant_value": {"Exception": "DenyGoldenImage"}},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_windows_virtual_machine.valid_vm_size_example",
				"mode": "managed",
				"type": "azurerm_windows_virtual_machine",
				"name": "valid_vm_size_example",
				"provider_config_key": "azurerm",
				"expressions": {
					"admin_password": {"constant_value": "P@$$w0rd1234!"},
					"admin_username": {"constant_value": "adminuser"},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "example-machine"},
					"network_interface_ids": {"references": [
						"azurerm_network_interface.example.id",
						"azurerm_network_interface.example",
					]},
					"os_disk": [{
						"caching": {"constant_value": "ReadWrite"},
						"storage_account_type": {"constant_value": "Standard_LRS"},
					}],
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"size": {"constant_value": "Standard_D4_v4"},
					"source_image_reference": [{
						"offer": {"constant_value": "WindowsServer"},
						"publisher": {"constant_value": "MicrosoftWindowsServer"},
						"sku": {"constant_value": "2016-Datacenter"},
						"version": {"constant_value": "latest"},
					}],
					"tags": {"constant_value": {"Exception": "DenyGoldenImage"}},
				},
				"schema_version": 0,
			},
		]},
	},
}
