# Rego test for Cosmos DB Restrict Public Access
# This rule denies CosmosDB resources from being created that do not set the public_network_access_enabled attribute to false
package rules.cosmos_db_restrict_public_access

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

test_restrict_public_access_requirement {
	pol := policy with input as mock_input
	resources := {p.id: p.valid | pol[p]}

	resources["azurerm_cosmosdb_account.valid"] == true
	resources["azurerm_cosmosdb_account.invalid"] == false
}

# Mock input is generated plan for cosmos_db_restrict_public_access.tf
mock_plan_input = {
	"format_version": "0.2",
	"terraform_version": "1.0.11",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "azurerm_cosmosdb_account.invalid",
			"mode": "managed",
			"type": "azurerm_cosmosdb_account",
			"name": "invalid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"access_key_metadata_writes_enabled": true,
				"analytical_storage_enabled": false,
				"capabilities": [
					{"name": "EnableAggregationPipeline"},
					{"name": "EnableMongo"},
					{"name": "MongoDBv3.4"},
					{"name": "mongoEnableDocLevelTTL"},
				],
				"capacity": [],
				"consistency_policy": [{
					"consistency_level": "BoundedStaleness",
					"max_interval_in_seconds": 10,
					"max_staleness_prefix": 200,
				}],
				"cors_rule": [],
				"default_identity_type": "FirstPartyIdentity",
				"enable_automatic_failover": true,
				"enable_free_tier": false,
				"enable_multiple_write_locations": false,
				"geo_location": [
					{
						"failover_priority": 0,
						"location": "eastus",
						"prefix": "",
						"zone_redundant": false,
					},
					{
						"failover_priority": 1,
						"location": "eastus",
						"prefix": "",
						"zone_redundant": false,
					},
				],
				"identity": [],
				"ip_range_filter": null,
				"is_virtual_network_filter_enabled": false,
				"key_vault_key_id": null,
				"kind": "GlobalDocumentDB",
				"local_authentication_disabled": false,
				"location": "eastus",
				"name": "tfex-cosmos-db-invalid",
				"network_acl_bypass_for_azure_services": false,
				"network_acl_bypass_ids": null,
				"offer_type": "Standard",
				"public_network_access_enabled": true,
				"resource_group_name": "terraform-example-resources",
				"tags": null,
				"timeouts": null,
				"virtual_network_rule": [],
			},
			"sensitive_values": {
				"analytical_storage": [],
				"backup": [],
				"capabilities": [
					{},
					{},
					{},
					{},
				],
				"capacity": [],
				"connection_strings": [],
				"consistency_policy": [{}],
				"cors_rule": [],
				"geo_location": [
					{},
					{},
				],
				"identity": [],
				"read_endpoints": [],
				"virtual_network_rule": [],
				"write_endpoints": [],
			},
		},
		{
			"address": "azurerm_cosmosdb_account.valid",
			"mode": "managed",
			"type": "azurerm_cosmosdb_account",
			"name": "valid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"access_key_metadata_writes_enabled": true,
				"analytical_storage_enabled": false,
				"capabilities": [
					{"name": "EnableAggregationPipeline"},
					{"name": "EnableMongo"},
					{"name": "MongoDBv3.4"},
					{"name": "mongoEnableDocLevelTTL"},
				],
				"capacity": [],
				"consistency_policy": [{
					"consistency_level": "BoundedStaleness",
					"max_interval_in_seconds": 10,
					"max_staleness_prefix": 200,
				}],
				"cors_rule": [],
				"default_identity_type": "FirstPartyIdentity",
				"enable_automatic_failover": true,
				"enable_free_tier": false,
				"enable_multiple_write_locations": false,
				"geo_location": [
					{
						"failover_priority": 0,
						"location": "eastus",
						"prefix": "",
						"zone_redundant": false,
					},
					{
						"failover_priority": 1,
						"location": "eastus",
						"prefix": "",
						"zone_redundant": false,
					},
				],
				"identity": [],
				"ip_range_filter": null,
				"is_virtual_network_filter_enabled": false,
				"key_vault_key_id": null,
				"kind": "GlobalDocumentDB",
				"local_authentication_disabled": false,
				"location": "eastus",
				"name": "tfex-cosmos-db-valid",
				"network_acl_bypass_for_azure_services": false,
				"network_acl_bypass_ids": null,
				"offer_type": "Standard",
				"public_network_access_enabled": false,
				"resource_group_name": "terraform-example-resources",
				"tags": null,
				"timeouts": null,
				"virtual_network_rule": [],
			},
			"sensitive_values": {
				"analytical_storage": [],
				"backup": [],
				"capabilities": [
					{},
					{},
					{},
					{},
				],
				"capacity": [],
				"connection_strings": [],
				"consistency_policy": [{}],
				"cors_rule": [],
				"geo_location": [
					{},
					{},
				],
				"identity": [],
				"read_endpoints": [],
				"virtual_network_rule": [],
				"write_endpoints": [],
			},
		},
		{
			"address": "azurerm_resource_group.rg",
			"mode": "managed",
			"type": "azurerm_resource_group",
			"name": "rg",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"location": "eastus",
				"name": "terraform-example-resources",
				"tags": null,
				"timeouts": null,
			},
			"sensitive_values": {},
		},
	]}},
	"resource_changes": [
		{
			"address": "azurerm_cosmosdb_account.invalid",
			"mode": "managed",
			"type": "azurerm_cosmosdb_account",
			"name": "invalid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"access_key_metadata_writes_enabled": true,
					"analytical_storage_enabled": false,
					"capabilities": [
						{"name": "EnableAggregationPipeline"},
						{"name": "EnableMongo"},
						{"name": "MongoDBv3.4"},
						{"name": "mongoEnableDocLevelTTL"},
					],
					"capacity": [],
					"consistency_policy": [{
						"consistency_level": "BoundedStaleness",
						"max_interval_in_seconds": 10,
						"max_staleness_prefix": 200,
					}],
					"cors_rule": [],
					"default_identity_type": "FirstPartyIdentity",
					"enable_automatic_failover": true,
					"enable_free_tier": false,
					"enable_multiple_write_locations": false,
					"geo_location": [
						{
							"failover_priority": 0,
							"location": "eastus",
							"prefix": "",
							"zone_redundant": false,
						},
						{
							"failover_priority": 1,
							"location": "eastus",
							"prefix": "",
							"zone_redundant": false,
						},
					],
					"identity": [],
					"ip_range_filter": null,
					"is_virtual_network_filter_enabled": false,
					"key_vault_key_id": null,
					"kind": "GlobalDocumentDB",
					"local_authentication_disabled": false,
					"location": "eastus",
					"name": "tfex-cosmos-db-invalid",
					"network_acl_bypass_for_azure_services": false,
					"network_acl_bypass_ids": null,
					"offer_type": "Standard",
					"public_network_access_enabled": true,
					"resource_group_name": "terraform-example-resources",
					"tags": null,
					"timeouts": null,
					"virtual_network_rule": [],
				},
				"after_unknown": {
					"analytical_storage": true,
					"backup": true,
					"capabilities": [
						{},
						{},
						{},
						{},
					],
					"capacity": [],
					"connection_strings": true,
					"consistency_policy": [{}],
					"cors_rule": [],
					"endpoint": true,
					"geo_location": [
						{"id": true},
						{"id": true},
					],
					"id": true,
					"identity": [],
					"mongo_server_version": true,
					"primary_key": true,
					"primary_master_key": true,
					"primary_readonly_key": true,
					"primary_readonly_master_key": true,
					"read_endpoints": true,
					"secondary_key": true,
					"secondary_master_key": true,
					"secondary_readonly_key": true,
					"secondary_readonly_master_key": true,
					"virtual_network_rule": [],
					"write_endpoints": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"analytical_storage": [],
					"backup": [],
					"capabilities": [
						{},
						{},
						{},
						{},
					],
					"capacity": [],
					"connection_strings": true,
					"consistency_policy": [{}],
					"cors_rule": [],
					"geo_location": [
						{},
						{},
					],
					"identity": [],
					"primary_key": true,
					"primary_master_key": true,
					"primary_readonly_key": true,
					"primary_readonly_master_key": true,
					"read_endpoints": [],
					"secondary_key": true,
					"secondary_master_key": true,
					"secondary_readonly_key": true,
					"secondary_readonly_master_key": true,
					"virtual_network_rule": [],
					"write_endpoints": [],
				},
			},
		},
		{
			"address": "azurerm_cosmosdb_account.valid",
			"mode": "managed",
			"type": "azurerm_cosmosdb_account",
			"name": "valid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"access_key_metadata_writes_enabled": true,
					"analytical_storage_enabled": false,
					"capabilities": [
						{"name": "EnableAggregationPipeline"},
						{"name": "EnableMongo"},
						{"name": "MongoDBv3.4"},
						{"name": "mongoEnableDocLevelTTL"},
					],
					"capacity": [],
					"consistency_policy": [{
						"consistency_level": "BoundedStaleness",
						"max_interval_in_seconds": 10,
						"max_staleness_prefix": 200,
					}],
					"cors_rule": [],
					"default_identity_type": "FirstPartyIdentity",
					"enable_automatic_failover": true,
					"enable_free_tier": false,
					"enable_multiple_write_locations": false,
					"geo_location": [
						{
							"failover_priority": 0,
							"location": "eastus",
							"prefix": "",
							"zone_redundant": false,
						},
						{
							"failover_priority": 1,
							"location": "eastus",
							"prefix": "",
							"zone_redundant": false,
						},
					],
					"identity": [],
					"ip_range_filter": null,
					"is_virtual_network_filter_enabled": false,
					"key_vault_key_id": null,
					"kind": "GlobalDocumentDB",
					"local_authentication_disabled": false,
					"location": "eastus",
					"name": "tfex-cosmos-db-valid",
					"network_acl_bypass_for_azure_services": false,
					"network_acl_bypass_ids": null,
					"offer_type": "Standard",
					"public_network_access_enabled": false,
					"resource_group_name": "terraform-example-resources",
					"tags": null,
					"timeouts": null,
					"virtual_network_rule": [],
				},
				"after_unknown": {
					"analytical_storage": true,
					"backup": true,
					"capabilities": [
						{},
						{},
						{},
						{},
					],
					"capacity": [],
					"connection_strings": true,
					"consistency_policy": [{}],
					"cors_rule": [],
					"endpoint": true,
					"geo_location": [
						{"id": true},
						{"id": true},
					],
					"id": true,
					"identity": [],
					"mongo_server_version": true,
					"primary_key": true,
					"primary_master_key": true,
					"primary_readonly_key": true,
					"primary_readonly_master_key": true,
					"read_endpoints": true,
					"secondary_key": true,
					"secondary_master_key": true,
					"secondary_readonly_key": true,
					"secondary_readonly_master_key": true,
					"virtual_network_rule": [],
					"write_endpoints": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"analytical_storage": [],
					"backup": [],
					"capabilities": [
						{},
						{},
						{},
						{},
					],
					"capacity": [],
					"connection_strings": true,
					"consistency_policy": [{}],
					"cors_rule": [],
					"geo_location": [
						{},
						{},
					],
					"identity": [],
					"primary_key": true,
					"primary_master_key": true,
					"primary_readonly_key": true,
					"primary_readonly_master_key": true,
					"read_endpoints": [],
					"secondary_key": true,
					"secondary_master_key": true,
					"secondary_readonly_key": true,
					"secondary_readonly_master_key": true,
					"virtual_network_rule": [],
					"write_endpoints": [],
				},
			},
		},
		{
			"address": "azurerm_resource_group.rg",
			"mode": "managed",
			"type": "azurerm_resource_group",
			"name": "rg",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"location": "eastus",
					"name": "terraform-example-resources",
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {"id": true},
				"before_sensitive": false,
				"after_sensitive": {},
			},
		},
	],
	"configuration": {
		"provider_config": {"azurerm": {
			"name": "azurerm",
			"version_constraint": "~> 2.0",
			"expressions": {"features": [{}]},
		}},
		"root_module": {"resources": [
			{
				"address": "azurerm_cosmosdb_account.invalid",
				"mode": "managed",
				"type": "azurerm_cosmosdb_account",
				"name": "invalid",
				"provider_config_key": "azurerm",
				"expressions": {
					"capabilities": [
						{"name": {"constant_value": "EnableAggregationPipeline"}},
						{"name": {"constant_value": "mongoEnableDocLevelTTL"}},
						{"name": {"constant_value": "MongoDBv3.4"}},
						{"name": {"constant_value": "EnableMongo"}},
					],
					"consistency_policy": [{
						"consistency_level": {"constant_value": "BoundedStaleness"},
						"max_interval_in_seconds": {"constant_value": 10},
						"max_staleness_prefix": {"constant_value": 200},
					}],
					"enable_automatic_failover": {"constant_value": true},
					"geo_location": [
						{
							"failover_priority": {"constant_value": 1},
							"location": {"references": [
								"azurerm_resource_group.rg.location",
								"azurerm_resource_group.rg",
							]},
						},
						{
							"failover_priority": {"constant_value": 0},
							"location": {"references": [
								"azurerm_resource_group.rg.location",
								"azurerm_resource_group.rg",
							]},
						},
					],
					"kind": {"constant_value": "GlobalDocumentDB"},
					"location": {"references": [
						"azurerm_resource_group.rg.location",
						"azurerm_resource_group.rg",
					]},
					"name": {"constant_value": "tfex-cosmos-db-invalid"},
					"offer_type": {"constant_value": "Standard"},
					"public_network_access_enabled": {"constant_value": true},
					"resource_group_name": {"references": [
						"azurerm_resource_group.rg.name",
						"azurerm_resource_group.rg",
					]},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_cosmosdb_account.valid",
				"mode": "managed",
				"type": "azurerm_cosmosdb_account",
				"name": "valid",
				"provider_config_key": "azurerm",
				"expressions": {
					"capabilities": [
						{"name": {"constant_value": "EnableAggregationPipeline"}},
						{"name": {"constant_value": "mongoEnableDocLevelTTL"}},
						{"name": {"constant_value": "MongoDBv3.4"}},
						{"name": {"constant_value": "EnableMongo"}},
					],
					"consistency_policy": [{
						"consistency_level": {"constant_value": "BoundedStaleness"},
						"max_interval_in_seconds": {"constant_value": 10},
						"max_staleness_prefix": {"constant_value": 200},
					}],
					"enable_automatic_failover": {"constant_value": true},
					"geo_location": [
						{
							"failover_priority": {"constant_value": 1},
							"location": {"references": [
								"azurerm_resource_group.rg.location",
								"azurerm_resource_group.rg",
							]},
						},
						{
							"failover_priority": {"constant_value": 0},
							"location": {"references": [
								"azurerm_resource_group.rg.location",
								"azurerm_resource_group.rg",
							]},
						},
					],
					"kind": {"constant_value": "GlobalDocumentDB"},
					"location": {"references": [
						"azurerm_resource_group.rg.location",
						"azurerm_resource_group.rg",
					]},
					"name": {"constant_value": "tfex-cosmos-db-valid"},
					"offer_type": {"constant_value": "Standard"},
					"public_network_access_enabled": {"constant_value": false},
					"resource_group_name": {"references": [
						"azurerm_resource_group.rg.name",
						"azurerm_resource_group.rg",
					]},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_resource_group.rg",
				"mode": "managed",
				"type": "azurerm_resource_group",
				"name": "rg",
				"provider_config_key": "azurerm",
				"expressions": {
					"location": {"constant_value": "eastus"},
					"name": {"constant_value": "terraform-example-resources"},
				},
				"schema_version": 0,
			},
		]},
	},
}
