# Rego test for Maria DB Require Geo Redundancy
# This rule denies MariaDB server resources from being created that do not utilize geo-redundancy
package rules.maria_db_require_geo_redundancy

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

test_geo_redundancy_requirement {
	pol := policy with input as mock_input
	resources := {p.id: p.valid | pol[p]}

	resources["azurerm_mariadb_server.valid"] == true
	resources["azurerm_mariadb_server.valid_basic_sku_not_compatible"] == true
	resources["azurerm_mariadb_server.invalid"] == false
}

# Mock input is generated plan for maria_db_require_geo_redundancy.tf
mock_plan_input = {
	"format_version": "0.2",
	"terraform_version": "1.0.11",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "azurerm_mariadb_server.invalid",
			"mode": "managed",
			"type": "azurerm_mariadb_server",
			"name": "invalid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"administrator_login": "mariadbadmin",
				"administrator_login_password": "H@Sh1CoR3!",
				"auto_grow_enabled": true,
				"backup_retention_days": 7,
				"create_mode": "Default",
				"creation_source_server_id": null,
				"geo_redundant_backup_enabled": false,
				"location": "eastus",
				"name": "example-mariadb-server-2",
				"public_network_access_enabled": false,
				"resource_group_name": "terraform-example-resources",
				"restore_point_in_time": null,
				"sku_name": "GP_Gen5_2",
				"ssl_enforcement_enabled": true,
				"storage_mb": 5120,
				"tags": null,
				"timeouts": null,
				"version": "10.2",
			},
			"sensitive_values": {"storage_profile": []},
		},
		{
			"address": "azurerm_mariadb_server.valid",
			"mode": "managed",
			"type": "azurerm_mariadb_server",
			"name": "valid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"administrator_login": "mariadbadmin",
				"administrator_login_password": "H@Sh1CoR3!",
				"auto_grow_enabled": true,
				"backup_retention_days": 7,
				"create_mode": "Default",
				"creation_source_server_id": null,
				"geo_redundant_backup_enabled": true,
				"location": "eastus",
				"name": "example-mariadb-server-1",
				"public_network_access_enabled": false,
				"resource_group_name": "terraform-example-resources",
				"restore_point_in_time": null,
				"sku_name": "GP_Gen5_2",
				"ssl_enforcement_enabled": true,
				"storage_mb": 5120,
				"tags": null,
				"timeouts": null,
				"version": "10.2",
			},
			"sensitive_values": {"storage_profile": []},
		},
		{
			"address": "azurerm_mariadb_server.valid_basic_sku_not_compatible",
			"mode": "managed",
			"type": "azurerm_mariadb_server",
			"name": "valid_basic_sku_not_compatible",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"administrator_login": "mariadbadmin",
				"administrator_login_password": "H@Sh1CoR3!",
				"auto_grow_enabled": true,
				"backup_retention_days": 7,
				"create_mode": "Default",
				"creation_source_server_id": null,
				"geo_redundant_backup_enabled": false,
				"location": "eastus",
				"name": "example-mariadb-server-3",
				"public_network_access_enabled": false,
				"resource_group_name": "terraform-example-resources",
				"restore_point_in_time": null,
				"sku_name": "B_Gen5_1",
				"ssl_enforcement_enabled": true,
				"storage_mb": 5120,
				"tags": null,
				"timeouts": null,
				"version": "10.2",
			},
			"sensitive_values": {"storage_profile": []},
		},
		{
			"address": "azurerm_resource_group.example",
			"mode": "managed",
			"type": "azurerm_resource_group",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"location": "eastus",
				"name": "terraform-example-resources",
				"tags": null,
				"timeouts": null,
			},
			"sensitive_values": {},
		},
	]}},
	"resource_changes": [
		{
			"address": "azurerm_mariadb_server.invalid",
			"mode": "managed",
			"type": "azurerm_mariadb_server",
			"name": "invalid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"administrator_login": "mariadbadmin",
					"administrator_login_password": "H@Sh1CoR3!",
					"auto_grow_enabled": true,
					"backup_retention_days": 7,
					"create_mode": "Default",
					"creation_source_server_id": null,
					"geo_redundant_backup_enabled": false,
					"location": "eastus",
					"name": "example-mariadb-server-2",
					"public_network_access_enabled": false,
					"resource_group_name": "terraform-example-resources",
					"restore_point_in_time": null,
					"sku_name": "GP_Gen5_2",
					"ssl_enforcement_enabled": true,
					"storage_mb": 5120,
					"tags": null,
					"timeouts": null,
					"version": "10.2",
				},
				"after_unknown": {
					"fqdn": true,
					"id": true,
					"ssl_enforcement": true,
					"storage_profile": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"administrator_login_password": true,
					"storage_profile": [],
				},
			},
		},
		{
			"address": "azurerm_mariadb_server.valid",
			"mode": "managed",
			"type": "azurerm_mariadb_server",
			"name": "valid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"administrator_login": "mariadbadmin",
					"administrator_login_password": "H@Sh1CoR3!",
					"auto_grow_enabled": true,
					"backup_retention_days": 7,
					"create_mode": "Default",
					"creation_source_server_id": null,
					"geo_redundant_backup_enabled": true,
					"location": "eastus",
					"name": "example-mariadb-server-1",
					"public_network_access_enabled": false,
					"resource_group_name": "terraform-example-resources",
					"restore_point_in_time": null,
					"sku_name": "GP_Gen5_2",
					"ssl_enforcement_enabled": true,
					"storage_mb": 5120,
					"tags": null,
					"timeouts": null,
					"version": "10.2",
				},
				"after_unknown": {
					"fqdn": true,
					"id": true,
					"ssl_enforcement": true,
					"storage_profile": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"administrator_login_password": true,
					"storage_profile": [],
				},
			},
		},
		{
			"address": "azurerm_mariadb_server.valid_basic_sku_not_compatible",
			"mode": "managed",
			"type": "azurerm_mariadb_server",
			"name": "valid_basic_sku_not_compatible",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"administrator_login": "mariadbadmin",
					"administrator_login_password": "H@Sh1CoR3!",
					"auto_grow_enabled": true,
					"backup_retention_days": 7,
					"create_mode": "Default",
					"creation_source_server_id": null,
					"geo_redundant_backup_enabled": false,
					"location": "eastus",
					"name": "example-mariadb-server-3",
					"public_network_access_enabled": false,
					"resource_group_name": "terraform-example-resources",
					"restore_point_in_time": null,
					"sku_name": "B_Gen5_1",
					"ssl_enforcement_enabled": true,
					"storage_mb": 5120,
					"tags": null,
					"timeouts": null,
					"version": "10.2",
				},
				"after_unknown": {
					"fqdn": true,
					"id": true,
					"ssl_enforcement": true,
					"storage_profile": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"administrator_login_password": true,
					"storage_profile": [],
				},
			},
		},
		{
			"address": "azurerm_resource_group.example",
			"mode": "managed",
			"type": "azurerm_resource_group",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"location": "eastus",
					"name": "terraform-example-resources",
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {"id": true},
				"before_sensitive": false,
				"after_sensitive": {},
			},
		},
	],
	"configuration": {
		"provider_config": {"azurerm": {
			"name": "azurerm",
			"version_constraint": "~> 2.0",
			"expressions": {"features": [{}]},
		}},
		"root_module": {"resources": [
			{
				"address": "azurerm_mariadb_server.invalid",
				"mode": "managed",
				"type": "azurerm_mariadb_server",
				"name": "invalid",
				"provider_config_key": "azurerm",
				"expressions": {
					"administrator_login": {"constant_value": "mariadbadmin"},
					"administrator_login_password": {"constant_value": "H@Sh1CoR3!"},
					"auto_grow_enabled": {"constant_value": true},
					"backup_retention_days": {"constant_value": 7},
					"geo_redundant_backup_enabled": {"constant_value": false},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "example-mariadb-server-2"},
					"public_network_access_enabled": {"constant_value": false},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"sku_name": {"constant_value": "GP_Gen5_2"},
					"ssl_enforcement_enabled": {"constant_value": true},
					"storage_mb": {"constant_value": 5120},
					"version": {"constant_value": "10.2"},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_mariadb_server.valid",
				"mode": "managed",
				"type": "azurerm_mariadb_server",
				"name": "valid",
				"provider_config_key": "azurerm",
				"expressions": {
					"administrator_login": {"constant_value": "mariadbadmin"},
					"administrator_login_password": {"constant_value": "H@Sh1CoR3!"},
					"auto_grow_enabled": {"constant_value": true},
					"backup_retention_days": {"constant_value": 7},
					"geo_redundant_backup_enabled": {"constant_value": true},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "example-mariadb-server-1"},
					"public_network_access_enabled": {"constant_value": false},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"sku_name": {"constant_value": "GP_Gen5_2"},
					"ssl_enforcement_enabled": {"constant_value": true},
					"storage_mb": {"constant_value": 5120},
					"version": {"constant_value": "10.2"},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_mariadb_server.valid_basic_sku_not_compatible",
				"mode": "managed",
				"type": "azurerm_mariadb_server",
				"name": "valid_basic_sku_not_compatible",
				"provider_config_key": "azurerm",
				"expressions": {
					"administrator_login": {"constant_value": "mariadbadmin"},
					"administrator_login_password": {"constant_value": "H@Sh1CoR3!"},
					"auto_grow_enabled": {"constant_value": true},
					"backup_retention_days": {"constant_value": 7},
					"geo_redundant_backup_enabled": {"constant_value": false},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "example-mariadb-server-3"},
					"public_network_access_enabled": {"constant_value": false},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"sku_name": {"constant_value": "B_Gen5_1"},
					"ssl_enforcement_enabled": {"constant_value": true},
					"storage_mb": {"constant_value": 5120},
					"version": {"constant_value": "10.2"},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_resource_group.example",
				"mode": "managed",
				"type": "azurerm_resource_group",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"location": {"constant_value": "eastus"},
					"name": {"constant_value": "terraform-example-resources"},
				},
				"schema_version": 0,
			},
		]},
	},
}
