# Rego test for SQL Require Geo Redundancy
# This rule denies SQL server resources from being created that do not utilize geo-redundancy with a failover group and SQL servers at different locations
package rules.sql_require_geo_redundancy

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

test_geo_redundancy_requirement {
	pol := policy with input as mock_input
	resources := {p.id: p.valid | pol[p]}

	resources["azurerm_sql_server.primary"] == true
	resources["azurerm_sql_server.secondary"] == true

	resources["azurerm_sql_server.primary_invalid_same_location"] == false
	resources["azurerm_sql_server.invalid"] == false
}

# Mock input is generated plan for sql_require_geo_redundancy.tf
mock_plan_input = {
	"format_version": "0.2",
	"terraform_version": "1.0.11",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "azurerm_resource_group.example",
			"mode": "managed",
			"type": "azurerm_resource_group",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"location": "eastus",
				"name": "terraform-example-resources",
				"tags": null,
				"timeouts": null,
			},
			"sensitive_values": {},
		},
		{
			"address": "azurerm_sql_database.db1",
			"mode": "managed",
			"type": "azurerm_sql_database",
			"name": "db1",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"create_mode": "Default",
				"import": [],
				"location": "eastus",
				"name": "db1",
				"read_scale": false,
				"resource_group_name": "terraform-example-resources",
				"server_name": "sql-primary",
				"tags": null,
				"timeouts": null,
				"zone_redundant": null,
			},
			"sensitive_values": {
				"extended_auditing_policy": [],
				"import": [],
				"threat_detection_policy": [],
			},
		},
		{
			"address": "azurerm_sql_database.db2",
			"mode": "managed",
			"type": "azurerm_sql_database",
			"name": "db2",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"create_mode": "Default",
				"import": [],
				"location": "eastus",
				"name": "db2",
				"read_scale": false,
				"resource_group_name": "terraform-example-resources",
				"server_name": "sql-primary-2",
				"tags": null,
				"timeouts": null,
				"zone_redundant": null,
			},
			"sensitive_values": {
				"extended_auditing_policy": [],
				"import": [],
				"threat_detection_policy": [],
			},
		},
		{
			"address": "azurerm_sql_failover_group.example",
			"mode": "managed",
			"type": "azurerm_sql_failover_group",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"name": "example-failover-group",
				"partner_servers": [{}],
				"read_write_endpoint_failover_policy": [{
					"grace_minutes": 60,
					"mode": "Automatic",
				}],
				"resource_group_name": "terraform-example-resources",
				"server_name": "sql-primary",
				"tags": null,
				"timeouts": null,
			},
			"sensitive_values": {
				"databases": [],
				"partner_servers": [{}],
				"read_write_endpoint_failover_policy": [{}],
				"readonly_endpoint_failover_policy": [],
			},
		},
		{
			"address": "azurerm_sql_failover_group.example_invalid",
			"mode": "managed",
			"type": "azurerm_sql_failover_group",
			"name": "example_invalid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"name": "example-failover-group",
				"partner_servers": [{}],
				"read_write_endpoint_failover_policy": [{
					"grace_minutes": 60,
					"mode": "Automatic",
				}],
				"resource_group_name": "terraform-example-resources",
				"server_name": "sql-primary-2",
				"tags": null,
				"timeouts": null,
			},
			"sensitive_values": {
				"databases": [],
				"partner_servers": [{}],
				"read_write_endpoint_failover_policy": [{}],
				"readonly_endpoint_failover_policy": [],
			},
		},
		{
			"address": "azurerm_sql_server.invalid",
			"mode": "managed",
			"type": "azurerm_sql_server",
			"name": "invalid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"administrator_login": "sqladmin",
				"administrator_login_password": "pa$$w0rd",
				"connection_policy": "Default",
				"identity": [],
				"location": "eastus",
				"name": "sql-primary-invalid",
				"resource_group_name": "terraform-example-resources",
				"tags": null,
				"timeouts": null,
				"version": "12.0",
			},
			"sensitive_values": {
				"extended_auditing_policy": [],
				"identity": [],
				"threat_detection_policy": [],
			},
		},
		{
			"address": "azurerm_sql_server.primary",
			"mode": "managed",
			"type": "azurerm_sql_server",
			"name": "primary",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"administrator_login": "sqladmin",
				"administrator_login_password": "pa$$w0rd",
				"connection_policy": "Default",
				"identity": [],
				"location": "eastus",
				"name": "sql-primary",
				"resource_group_name": "terraform-example-resources",
				"tags": null,
				"timeouts": null,
				"version": "12.0",
			},
			"sensitive_values": {
				"extended_auditing_policy": [],
				"identity": [],
				"threat_detection_policy": [],
			},
		},
		{
			"address": "azurerm_sql_server.primary_invalid_same_location",
			"mode": "managed",
			"type": "azurerm_sql_server",
			"name": "primary_invalid_same_location",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"administrator_login": "sqladmin",
				"administrator_login_password": "pa$$w0rd",
				"connection_policy": "Default",
				"identity": [],
				"location": "eastus",
				"name": "sql-primary-2",
				"resource_group_name": "terraform-example-resources",
				"tags": null,
				"timeouts": null,
				"version": "12.0",
			},
			"sensitive_values": {
				"extended_auditing_policy": [],
				"identity": [],
				"threat_detection_policy": [],
			},
		},
		{
			"address": "azurerm_sql_server.secondary",
			"mode": "managed",
			"type": "azurerm_sql_server",
			"name": "secondary",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"administrator_login": "sqladmin",
				"administrator_login_password": "pa$$w0rd",
				"connection_policy": "Default",
				"identity": [],
				"location": "northeurope",
				"name": "sql-secondary",
				"resource_group_name": "terraform-example-resources",
				"tags": null,
				"timeouts": null,
				"version": "12.0",
			},
			"sensitive_values": {
				"extended_auditing_policy": [],
				"identity": [],
				"threat_detection_policy": [],
			},
		},
		{
			"address": "azurerm_sql_server.secondary_invalid_same_location",
			"mode": "managed",
			"type": "azurerm_sql_server",
			"name": "secondary_invalid_same_location",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"administrator_login": "sqladmin",
				"administrator_login_password": "pa$$w0rd",
				"connection_policy": "Default",
				"identity": [],
				"location": "eastus",
				"name": "sql-secondary-2",
				"resource_group_name": "terraform-example-resources",
				"tags": null,
				"timeouts": null,
				"version": "12.0",
			},
			"sensitive_values": {
				"extended_auditing_policy": [],
				"identity": [],
				"threat_detection_policy": [],
			},
		},
	]}},
	"resource_changes": [
		{
			"address": "azurerm_resource_group.example",
			"mode": "managed",
			"type": "azurerm_resource_group",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"location": "eastus",
					"name": "terraform-example-resources",
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {"id": true},
				"before_sensitive": false,
				"after_sensitive": {},
			},
		},
		{
			"address": "azurerm_sql_database.db1",
			"mode": "managed",
			"type": "azurerm_sql_database",
			"name": "db1",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"create_mode": "Default",
					"import": [],
					"location": "eastus",
					"name": "db1",
					"read_scale": false,
					"resource_group_name": "terraform-example-resources",
					"server_name": "sql-primary",
					"tags": null,
					"timeouts": null,
					"zone_redundant": null,
				},
				"after_unknown": {
					"collation": true,
					"creation_date": true,
					"default_secondary_location": true,
					"edition": true,
					"elastic_pool_name": true,
					"encryption": true,
					"extended_auditing_policy": true,
					"id": true,
					"import": [],
					"max_size_bytes": true,
					"max_size_gb": true,
					"requested_service_objective_id": true,
					"requested_service_objective_name": true,
					"restore_point_in_time": true,
					"source_database_deletion_date": true,
					"source_database_id": true,
					"threat_detection_policy": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"extended_auditing_policy": [],
					"import": [],
					"threat_detection_policy": [],
				},
			},
		},
		{
			"address": "azurerm_sql_database.db2",
			"mode": "managed",
			"type": "azurerm_sql_database",
			"name": "db2",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"create_mode": "Default",
					"import": [],
					"location": "eastus",
					"name": "db2",
					"read_scale": false,
					"resource_group_name": "terraform-example-resources",
					"server_name": "sql-primary-2",
					"tags": null,
					"timeouts": null,
					"zone_redundant": null,
				},
				"after_unknown": {
					"collation": true,
					"creation_date": true,
					"default_secondary_location": true,
					"edition": true,
					"elastic_pool_name": true,
					"encryption": true,
					"extended_auditing_policy": true,
					"id": true,
					"import": [],
					"max_size_bytes": true,
					"max_size_gb": true,
					"requested_service_objective_id": true,
					"requested_service_objective_name": true,
					"restore_point_in_time": true,
					"source_database_deletion_date": true,
					"source_database_id": true,
					"threat_detection_policy": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"extended_auditing_policy": [],
					"import": [],
					"threat_detection_policy": [],
				},
			},
		},
		{
			"address": "azurerm_sql_failover_group.example",
			"mode": "managed",
			"type": "azurerm_sql_failover_group",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"name": "example-failover-group",
					"partner_servers": [{}],
					"read_write_endpoint_failover_policy": [{
						"grace_minutes": 60,
						"mode": "Automatic",
					}],
					"resource_group_name": "terraform-example-resources",
					"server_name": "sql-primary",
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {
					"databases": true,
					"id": true,
					"location": true,
					"partner_servers": [{
						"id": true,
						"location": true,
						"role": true,
					}],
					"read_write_endpoint_failover_policy": [{}],
					"readonly_endpoint_failover_policy": true,
					"role": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"databases": [],
					"partner_servers": [{}],
					"read_write_endpoint_failover_policy": [{}],
					"readonly_endpoint_failover_policy": [],
				},
			},
		},
		{
			"address": "azurerm_sql_failover_group.example_invalid",
			"mode": "managed",
			"type": "azurerm_sql_failover_group",
			"name": "example_invalid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"name": "example-failover-group",
					"partner_servers": [{}],
					"read_write_endpoint_failover_policy": [{
						"grace_minutes": 60,
						"mode": "Automatic",
					}],
					"resource_group_name": "terraform-example-resources",
					"server_name": "sql-primary-2",
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {
					"databases": true,
					"id": true,
					"location": true,
					"partner_servers": [{
						"id": true,
						"location": true,
						"role": true,
					}],
					"read_write_endpoint_failover_policy": [{}],
					"readonly_endpoint_failover_policy": true,
					"role": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"databases": [],
					"partner_servers": [{}],
					"read_write_endpoint_failover_policy": [{}],
					"readonly_endpoint_failover_policy": [],
				},
			},
		},
		{
			"address": "azurerm_sql_server.invalid",
			"mode": "managed",
			"type": "azurerm_sql_server",
			"name": "invalid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"administrator_login": "sqladmin",
					"administrator_login_password": "pa$$w0rd",
					"connection_policy": "Default",
					"identity": [],
					"location": "eastus",
					"name": "sql-primary-invalid",
					"resource_group_name": "terraform-example-resources",
					"tags": null,
					"timeouts": null,
					"version": "12.0",
				},
				"after_unknown": {
					"extended_auditing_policy": true,
					"fully_qualified_domain_name": true,
					"id": true,
					"identity": [],
					"threat_detection_policy": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"administrator_login_password": true,
					"extended_auditing_policy": [],
					"identity": [],
					"threat_detection_policy": [],
				},
			},
		},
		{
			"address": "azurerm_sql_server.primary",
			"mode": "managed",
			"type": "azurerm_sql_server",
			"name": "primary",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"administrator_login": "sqladmin",
					"administrator_login_password": "pa$$w0rd",
					"connection_policy": "Default",
					"identity": [],
					"location": "eastus",
					"name": "sql-primary",
					"resource_group_name": "terraform-example-resources",
					"tags": null,
					"timeouts": null,
					"version": "12.0",
				},
				"after_unknown": {
					"extended_auditing_policy": true,
					"fully_qualified_domain_name": true,
					"id": true,
					"identity": [],
					"threat_detection_policy": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"administrator_login_password": true,
					"extended_auditing_policy": [],
					"identity": [],
					"threat_detection_policy": [],
				},
			},
		},
		{
			"address": "azurerm_sql_server.primary_invalid_same_location",
			"mode": "managed",
			"type": "azurerm_sql_server",
			"name": "primary_invalid_same_location",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"administrator_login": "sqladmin",
					"administrator_login_password": "pa$$w0rd",
					"connection_policy": "Default",
					"identity": [],
					"location": "eastus",
					"name": "sql-primary-2",
					"resource_group_name": "terraform-example-resources",
					"tags": null,
					"timeouts": null,
					"version": "12.0",
				},
				"after_unknown": {
					"extended_auditing_policy": true,
					"fully_qualified_domain_name": true,
					"id": true,
					"identity": [],
					"threat_detection_policy": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"administrator_login_password": true,
					"extended_auditing_policy": [],
					"identity": [],
					"threat_detection_policy": [],
				},
			},
		},
		{
			"address": "azurerm_sql_server.secondary",
			"mode": "managed",
			"type": "azurerm_sql_server",
			"name": "secondary",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"administrator_login": "sqladmin",
					"administrator_login_password": "pa$$w0rd",
					"connection_policy": "Default",
					"identity": [],
					"location": "northeurope",
					"name": "sql-secondary",
					"resource_group_name": "terraform-example-resources",
					"tags": null,
					"timeouts": null,
					"version": "12.0",
				},
				"after_unknown": {
					"extended_auditing_policy": true,
					"fully_qualified_domain_name": true,
					"id": true,
					"identity": [],
					"threat_detection_policy": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"administrator_login_password": true,
					"extended_auditing_policy": [],
					"identity": [],
					"threat_detection_policy": [],
				},
			},
		},
		{
			"address": "azurerm_sql_server.secondary_invalid_same_location",
			"mode": "managed",
			"type": "azurerm_sql_server",
			"name": "secondary_invalid_same_location",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"administrator_login": "sqladmin",
					"administrator_login_password": "pa$$w0rd",
					"connection_policy": "Default",
					"identity": [],
					"location": "eastus",
					"name": "sql-secondary-2",
					"resource_group_name": "terraform-example-resources",
					"tags": null,
					"timeouts": null,
					"version": "12.0",
				},
				"after_unknown": {
					"extended_auditing_policy": true,
					"fully_qualified_domain_name": true,
					"id": true,
					"identity": [],
					"threat_detection_policy": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"administrator_login_password": true,
					"extended_auditing_policy": [],
					"identity": [],
					"threat_detection_policy": [],
				},
			},
		},
	],
	"configuration": {
		"provider_config": {"azurerm": {
			"name": "azurerm",
			"version_constraint": "~> 2.0",
			"expressions": {"features": [{}]},
		}},
		"root_module": {"resources": [
			{
				"address": "azurerm_resource_group.example",
				"mode": "managed",
				"type": "azurerm_resource_group",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"location": {"constant_value": "eastus"},
					"name": {"constant_value": "terraform-example-resources"},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_sql_database.db1",
				"mode": "managed",
				"type": "azurerm_sql_database",
				"name": "db1",
				"provider_config_key": "azurerm",
				"expressions": {
					"location": {"references": [
						"azurerm_sql_server.primary.location",
						"azurerm_sql_server.primary",
					]},
					"name": {"constant_value": "db1"},
					"resource_group_name": {"references": [
						"azurerm_sql_server.primary.resource_group_name",
						"azurerm_sql_server.primary",
					]},
					"server_name": {"references": [
						"azurerm_sql_server.primary.name",
						"azurerm_sql_server.primary",
					]},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_sql_database.db2",
				"mode": "managed",
				"type": "azurerm_sql_database",
				"name": "db2",
				"provider_config_key": "azurerm",
				"expressions": {
					"location": {"references": [
						"azurerm_sql_server.primary_invalid_same_location.location",
						"azurerm_sql_server.primary_invalid_same_location",
					]},
					"name": {"constant_value": "db2"},
					"resource_group_name": {"references": [
						"azurerm_sql_server.primary_invalid_same_location.resource_group_name",
						"azurerm_sql_server.primary_invalid_same_location",
					]},
					"server_name": {"references": [
						"azurerm_sql_server.primary_invalid_same_location.name",
						"azurerm_sql_server.primary_invalid_same_location",
					]},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_sql_failover_group.example",
				"mode": "managed",
				"type": "azurerm_sql_failover_group",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"databases": {"references": [
						"azurerm_sql_database.db1.id",
						"azurerm_sql_database.db1",
					]},
					"name": {"constant_value": "example-failover-group"},
					"partner_servers": [{"id": {"references": [
						"azurerm_sql_server.secondary.id",
						"azurerm_sql_server.secondary",
					]}}],
					"read_write_endpoint_failover_policy": [{
						"grace_minutes": {"constant_value": 60},
						"mode": {"constant_value": "Automatic"},
					}],
					"resource_group_name": {"references": [
						"azurerm_sql_server.primary.resource_group_name",
						"azurerm_sql_server.primary",
					]},
					"server_name": {"references": [
						"azurerm_sql_server.primary.name",
						"azurerm_sql_server.primary",
					]},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_sql_failover_group.example_invalid",
				"mode": "managed",
				"type": "azurerm_sql_failover_group",
				"name": "example_invalid",
				"provider_config_key": "azurerm",
				"expressions": {
					"databases": {"references": [
						"azurerm_sql_database.db2.id",
						"azurerm_sql_database.db2",
					]},
					"name": {"constant_value": "example-failover-group"},
					"partner_servers": [{"id": {"references": [
						"azurerm_sql_server.secondary_invalid_same_location.id",
						"azurerm_sql_server.secondary_invalid_same_location",
					]}}],
					"read_write_endpoint_failover_policy": [{
						"grace_minutes": {"constant_value": 60},
						"mode": {"constant_value": "Automatic"},
					}],
					"resource_group_name": {"references": [
						"azurerm_sql_server.primary_invalid_same_location.resource_group_name",
						"azurerm_sql_server.primary_invalid_same_location",
					]},
					"server_name": {"references": [
						"azurerm_sql_server.primary_invalid_same_location.name",
						"azurerm_sql_server.primary_invalid_same_location",
					]},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_sql_server.invalid",
				"mode": "managed",
				"type": "azurerm_sql_server",
				"name": "invalid",
				"provider_config_key": "azurerm",
				"expressions": {
					"administrator_login": {"constant_value": "sqladmin"},
					"administrator_login_password": {"constant_value": "pa$$w0rd"},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "sql-primary-invalid"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"version": {"constant_value": "12.0"},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_sql_server.primary",
				"mode": "managed",
				"type": "azurerm_sql_server",
				"name": "primary",
				"provider_config_key": "azurerm",
				"expressions": {
					"administrator_login": {"constant_value": "sqladmin"},
					"administrator_login_password": {"constant_value": "pa$$w0rd"},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "sql-primary"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"version": {"constant_value": "12.0"},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_sql_server.primary_invalid_same_location",
				"mode": "managed",
				"type": "azurerm_sql_server",
				"name": "primary_invalid_same_location",
				"provider_config_key": "azurerm",
				"expressions": {
					"administrator_login": {"constant_value": "sqladmin"},
					"administrator_login_password": {"constant_value": "pa$$w0rd"},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "sql-primary-2"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"version": {"constant_value": "12.0"},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_sql_server.secondary",
				"mode": "managed",
				"type": "azurerm_sql_server",
				"name": "secondary",
				"provider_config_key": "azurerm",
				"expressions": {
					"administrator_login": {"constant_value": "sqladmin"},
					"administrator_login_password": {"constant_value": "pa$$w0rd"},
					"location": {"constant_value": "northeurope"},
					"name": {"constant_value": "sql-secondary"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"version": {"constant_value": "12.0"},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_sql_server.secondary_invalid_same_location",
				"mode": "managed",
				"type": "azurerm_sql_server",
				"name": "secondary_invalid_same_location",
				"provider_config_key": "azurerm",
				"expressions": {
					"administrator_login": {"constant_value": "sqladmin"},
					"administrator_login_password": {"constant_value": "pa$$w0rd"},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "sql-secondary-2"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"version": {"constant_value": "12.0"},
				},
				"schema_version": 0,
			},
		]},
	},
}
