# Rego test for Databricks Require CMK
# This rule denies databricks workspace resources from being created that do not require CMK to encrypt the databricks data plane for premium SKU workspaces
package rules.databricks_require_cmk

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

test_cmk_requirement {
	pol := policy with input as mock_input
	resources := {p.id: p.valid | pol[p]}

	resources["azurerm_databricks_workspace.valid"] == true
	resources["azurerm_databricks_workspace.valid_feature_not_available_with_sku"] == true

	resources["azurerm_databricks_workspace.invalid"] == false
}

# Mock input is generated plan for databricks_require_cmk.tf
mock_plan_input = {
	"format_version": "0.2",
	"terraform_version": "1.0.11",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "azurerm_databricks_workspace.invalid",
			"mode": "managed",
			"type": "azurerm_databricks_workspace",
			"name": "invalid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"customer_managed_key_enabled": false,
				"infrastructure_encryption_enabled": false,
				"load_balancer_backend_address_pool_id": null,
				"location": "eastus",
				"managed_services_cmk_key_vault_key_id": null,
				"name": "databricks-test-3",
				"public_network_access_enabled": true,
				"resource_group_name": "example-resources",
				"sku": "premium",
				"tags": {"Environment": "Production"},
				"timeouts": null,
			},
			"sensitive_values": {
				"custom_parameters": [],
				"storage_account_identity": [],
				"tags": {},
			},
		},
		{
			"address": "azurerm_databricks_workspace.valid",
			"mode": "managed",
			"type": "azurerm_databricks_workspace",
			"name": "valid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"customer_managed_key_enabled": true,
				"infrastructure_encryption_enabled": false,
				"load_balancer_backend_address_pool_id": null,
				"location": "eastus",
				"managed_services_cmk_key_vault_key_id": null,
				"name": "databricks-test-1",
				"public_network_access_enabled": true,
				"resource_group_name": "example-resources",
				"sku": "premium",
				"tags": {"Environment": "Production"},
				"timeouts": null,
			},
			"sensitive_values": {
				"custom_parameters": [],
				"storage_account_identity": [],
				"tags": {},
			},
		},
		{
			"address": "azurerm_databricks_workspace.valid_feature_not_available_with_sku",
			"mode": "managed",
			"type": "azurerm_databricks_workspace",
			"name": "valid_feature_not_available_with_sku",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"customer_managed_key_enabled": false,
				"infrastructure_encryption_enabled": false,
				"load_balancer_backend_address_pool_id": null,
				"location": "eastus",
				"managed_services_cmk_key_vault_key_id": null,
				"name": "databricks-test-2",
				"public_network_access_enabled": true,
				"resource_group_name": "example-resources",
				"sku": "standard",
				"tags": {"Environment": "Production"},
				"timeouts": null,
			},
			"sensitive_values": {
				"custom_parameters": [],
				"storage_account_identity": [],
				"tags": {},
			},
		},
		{
			"address": "azurerm_databricks_workspace_customer_managed_key.example",
			"mode": "managed",
			"type": "azurerm_databricks_workspace_customer_managed_key",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {"timeouts": null},
			"sensitive_values": {},
		},
		{
			"address": "azurerm_key_vault.example",
			"mode": "managed",
			"type": "azurerm_key_vault",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 2,
			"values": {
				"contact": [],
				"enable_rbac_authorization": null,
				"enabled_for_deployment": null,
				"enabled_for_disk_encryption": null,
				"enabled_for_template_deployment": null,
				"location": "eastus",
				"name": "examplekeyvault",
				"purge_protection_enabled": true,
				"resource_group_name": "example-resources",
				"sku_name": "premium",
				"soft_delete_retention_days": 90,
				"tags": null,
				"tenant_id": "791b26cb-3fdf-47c3-b85d-bd9f037e3e7f",
				"timeouts": null,
			},
			"sensitive_values": {
				"access_policy": [],
				"contact": [],
				"network_acls": [],
			},
		},
		{
			"address": "azurerm_key_vault_access_policy.databricks",
			"mode": "managed",
			"type": "azurerm_key_vault_access_policy",
			"name": "databricks",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"application_id": null,
				"certificate_permissions": null,
				"key_permissions": [
					"get",
					"unwrapKey",
					"wrapKey",
				],
				"secret_permissions": null,
				"storage_permissions": null,
				"timeouts": null,
			},
			"sensitive_values": {"key_permissions": [
				false,
				false,
				false,
			]},
		},
		{
			"address": "azurerm_key_vault_access_policy.terraform",
			"mode": "managed",
			"type": "azurerm_key_vault_access_policy",
			"name": "terraform",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"application_id": null,
				"certificate_permissions": null,
				"key_permissions": [
					"get",
					"list",
					"create",
					"decrypt",
					"encrypt",
					"sign",
					"unwrapKey",
					"verify",
					"wrapKey",
					"delete",
					"restore",
					"recover",
					"update",
					"purge",
				],
				"object_id": "a291900c-9d00-4b0d-8d61-b397685458a1",
				"secret_permissions": null,
				"storage_permissions": null,
				"tenant_id": "791b26cb-3fdf-47c3-b85d-bd9f037e3e7f",
				"timeouts": null,
			},
			"sensitive_values": {"key_permissions": [
				false,
				false,
				false,
				false,
				false,
				false,
				false,
				false,
				false,
				false,
				false,
				false,
				false,
				false,
			]},
		},
		{
			"address": "azurerm_key_vault_key.example",
			"mode": "managed",
			"type": "azurerm_key_vault_key",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"expiration_date": null,
				"key_opts": [
					"decrypt",
					"encrypt",
					"sign",
					"unwrapKey",
					"verify",
					"wrapKey",
				],
				"key_size": 2048,
				"key_type": "RSA",
				"name": "example-certificate",
				"not_before_date": null,
				"tags": null,
				"timeouts": null,
			},
			"sensitive_values": {"key_opts": [
				false,
				false,
				false,
				false,
				false,
				false,
			]},
		},
		{
			"address": "azurerm_resource_group.example",
			"mode": "managed",
			"type": "azurerm_resource_group",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"location": "eastus",
				"name": "example-resources",
				"tags": null,
				"timeouts": null,
			},
			"sensitive_values": {},
		},
	]}},
	"resource_changes": [
		{
			"address": "azurerm_databricks_workspace.invalid",
			"mode": "managed",
			"type": "azurerm_databricks_workspace",
			"name": "invalid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"customer_managed_key_enabled": false,
					"infrastructure_encryption_enabled": false,
					"load_balancer_backend_address_pool_id": null,
					"location": "eastus",
					"managed_services_cmk_key_vault_key_id": null,
					"name": "databricks-test-3",
					"public_network_access_enabled": true,
					"resource_group_name": "example-resources",
					"sku": "premium",
					"tags": {"Environment": "Production"},
					"timeouts": null,
				},
				"after_unknown": {
					"custom_parameters": true,
					"id": true,
					"managed_resource_group_id": true,
					"managed_resource_group_name": true,
					"network_security_group_rules_required": true,
					"storage_account_identity": true,
					"tags": {},
					"workspace_id": true,
					"workspace_url": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"custom_parameters": [],
					"storage_account_identity": [],
					"tags": {},
				},
			},
		},
		{
			"address": "azurerm_databricks_workspace.valid",
			"mode": "managed",
			"type": "azurerm_databricks_workspace",
			"name": "valid",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"customer_managed_key_enabled": true,
					"infrastructure_encryption_enabled": false,
					"load_balancer_backend_address_pool_id": null,
					"location": "eastus",
					"managed_services_cmk_key_vault_key_id": null,
					"name": "databricks-test-1",
					"public_network_access_enabled": true,
					"resource_group_name": "example-resources",
					"sku": "premium",
					"tags": {"Environment": "Production"},
					"timeouts": null,
				},
				"after_unknown": {
					"custom_parameters": true,
					"id": true,
					"managed_resource_group_id": true,
					"managed_resource_group_name": true,
					"network_security_group_rules_required": true,
					"storage_account_identity": true,
					"tags": {},
					"workspace_id": true,
					"workspace_url": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"custom_parameters": [],
					"storage_account_identity": [],
					"tags": {},
				},
			},
		},
		{
			"address": "azurerm_databricks_workspace.valid_feature_not_available_with_sku",
			"mode": "managed",
			"type": "azurerm_databricks_workspace",
			"name": "valid_feature_not_available_with_sku",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"customer_managed_key_enabled": false,
					"infrastructure_encryption_enabled": false,
					"load_balancer_backend_address_pool_id": null,
					"location": "eastus",
					"managed_services_cmk_key_vault_key_id": null,
					"name": "databricks-test-2",
					"public_network_access_enabled": true,
					"resource_group_name": "example-resources",
					"sku": "standard",
					"tags": {"Environment": "Production"},
					"timeouts": null,
				},
				"after_unknown": {
					"custom_parameters": true,
					"id": true,
					"managed_resource_group_id": true,
					"managed_resource_group_name": true,
					"network_security_group_rules_required": true,
					"storage_account_identity": true,
					"tags": {},
					"workspace_id": true,
					"workspace_url": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"custom_parameters": [],
					"storage_account_identity": [],
					"tags": {},
				},
			},
		},
		{
			"address": "azurerm_databricks_workspace_customer_managed_key.example",
			"mode": "managed",
			"type": "azurerm_databricks_workspace_customer_managed_key",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {"timeouts": null},
				"after_unknown": {
					"id": true,
					"key_vault_key_id": true,
					"workspace_id": true,
				},
				"before_sensitive": false,
				"after_sensitive": {},
			},
		},
		{
			"address": "azurerm_key_vault.example",
			"mode": "managed",
			"type": "azurerm_key_vault",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"contact": [],
					"enable_rbac_authorization": null,
					"enabled_for_deployment": null,
					"enabled_for_disk_encryption": null,
					"enabled_for_template_deployment": null,
					"location": "eastus",
					"name": "examplekeyvault",
					"purge_protection_enabled": true,
					"resource_group_name": "example-resources",
					"sku_name": "premium",
					"soft_delete_retention_days": 90,
					"tags": null,
					"tenant_id": "791b26cb-3fdf-47c3-b85d-bd9f037e3e7f",
					"timeouts": null,
				},
				"after_unknown": {
					"access_policy": true,
					"contact": [],
					"id": true,
					"network_acls": true,
					"soft_delete_enabled": true,
					"vault_uri": true,
				},
				"before_sensitive": false,
				"after_sensitive": {
					"access_policy": [],
					"contact": [],
					"network_acls": [],
				},
			},
		},
		{
			"address": "azurerm_key_vault_access_policy.databricks",
			"mode": "managed",
			"type": "azurerm_key_vault_access_policy",
			"name": "databricks",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"application_id": null,
					"certificate_permissions": null,
					"key_permissions": [
						"get",
						"unwrapKey",
						"wrapKey",
					],
					"secret_permissions": null,
					"storage_permissions": null,
					"timeouts": null,
				},
				"after_unknown": {
					"id": true,
					"key_permissions": [
						false,
						false,
						false,
					],
					"key_vault_id": true,
					"object_id": true,
					"tenant_id": true,
				},
				"before_sensitive": false,
				"after_sensitive": {"key_permissions": [
					false,
					false,
					false,
				]},
			},
		},
		{
			"address": "azurerm_key_vault_access_policy.terraform",
			"mode": "managed",
			"type": "azurerm_key_vault_access_policy",
			"name": "terraform",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"application_id": null,
					"certificate_permissions": null,
					"key_permissions": [
						"get",
						"list",
						"create",
						"decrypt",
						"encrypt",
						"sign",
						"unwrapKey",
						"verify",
						"wrapKey",
						"delete",
						"restore",
						"recover",
						"update",
						"purge",
					],
					"object_id": "a291900c-9d00-4b0d-8d61-b397685458a1",
					"secret_permissions": null,
					"storage_permissions": null,
					"tenant_id": "791b26cb-3fdf-47c3-b85d-bd9f037e3e7f",
					"timeouts": null,
				},
				"after_unknown": {
					"id": true,
					"key_permissions": [
						false,
						false,
						false,
						false,
						false,
						false,
						false,
						false,
						false,
						false,
						false,
						false,
						false,
						false,
					],
					"key_vault_id": true,
				},
				"before_sensitive": false,
				"after_sensitive": {"key_permissions": [
					false,
					false,
					false,
					false,
					false,
					false,
					false,
					false,
					false,
					false,
					false,
					false,
					false,
					false,
				]},
			},
		},
		{
			"address": "azurerm_key_vault_key.example",
			"mode": "managed",
			"type": "azurerm_key_vault_key",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"expiration_date": null,
					"key_opts": [
						"decrypt",
						"encrypt",
						"sign",
						"unwrapKey",
						"verify",
						"wrapKey",
					],
					"key_size": 2048,
					"key_type": "RSA",
					"name": "example-certificate",
					"not_before_date": null,
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {
					"curve": true,
					"e": true,
					"id": true,
					"key_opts": [
						false,
						false,
						false,
						false,
						false,
						false,
					],
					"key_vault_id": true,
					"n": true,
					"public_key_openssh": true,
					"public_key_pem": true,
					"version": true,
					"versionless_id": true,
					"x": true,
					"y": true,
				},
				"before_sensitive": false,
				"after_sensitive": {"key_opts": [
					false,
					false,
					false,
					false,
					false,
					false,
				]},
			},
		},
		{
			"address": "azurerm_resource_group.example",
			"mode": "managed",
			"type": "azurerm_resource_group",
			"name": "example",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"location": "eastus",
					"name": "example-resources",
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {"id": true},
				"before_sensitive": false,
				"after_sensitive": {},
			},
		},
	],
	"prior_state": {
		"format_version": "0.2",
		"terraform_version": "1.0.11",
		"values": {"root_module": {"resources": [{
			"address": "data.azurerm_client_config.current",
			"mode": "data",
			"type": "azurerm_client_config",
			"name": "current",
			"provider_name": "registry.terraform.io/hashicorp/azurerm",
			"schema_version": 0,
			"values": {
				"client_id": "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
				"id": "2021-12-03 14:31:58.541248 +0000 UTC",
				"object_id": "a291900c-9d00-4b0d-8d61-b397685458a1",
				"subscription_id": "22377fc4-7da9-4791-bb5d-6908116916a5",
				"tenant_id": "791b26cb-3fdf-47c3-b85d-bd9f037e3e7f",
				"timeouts": null,
			},
			"sensitive_values": {},
		}]}},
	},
	"configuration": {
		"provider_config": {"azurerm": {
			"name": "azurerm",
			"version_constraint": "~> 2.0",
			"expressions": {"features": [{}]},
		}},
		"root_module": {"resources": [
			{
				"address": "azurerm_databricks_workspace.invalid",
				"mode": "managed",
				"type": "azurerm_databricks_workspace",
				"name": "invalid",
				"provider_config_key": "azurerm",
				"expressions": {
					"customer_managed_key_enabled": {"constant_value": false},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "databricks-test-3"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"sku": {"constant_value": "premium"},
					"tags": {"constant_value": {"Environment": "Production"}},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_databricks_workspace.valid",
				"mode": "managed",
				"type": "azurerm_databricks_workspace",
				"name": "valid",
				"provider_config_key": "azurerm",
				"expressions": {
					"customer_managed_key_enabled": {"constant_value": true},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "databricks-test-1"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"sku": {"constant_value": "premium"},
					"tags": {"constant_value": {"Environment": "Production"}},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_databricks_workspace.valid_feature_not_available_with_sku",
				"mode": "managed",
				"type": "azurerm_databricks_workspace",
				"name": "valid_feature_not_available_with_sku",
				"provider_config_key": "azurerm",
				"expressions": {
					"customer_managed_key_enabled": {"constant_value": false},
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "databricks-test-2"},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"sku": {"constant_value": "standard"},
					"tags": {"constant_value": {"Environment": "Production"}},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_databricks_workspace_customer_managed_key.example",
				"mode": "managed",
				"type": "azurerm_databricks_workspace_customer_managed_key",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"key_vault_key_id": {"references": [
						"azurerm_key_vault_key.example.id",
						"azurerm_key_vault_key.example",
					]},
					"workspace_id": {"references": [
						"azurerm_databricks_workspace.valid.id",
						"azurerm_databricks_workspace.valid",
					]},
				},
				"schema_version": 0,
				"depends_on": ["azurerm_key_vault_access_policy.databricks"],
			},
			{
				"address": "azurerm_key_vault.example",
				"mode": "managed",
				"type": "azurerm_key_vault",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"location": {"references": [
						"azurerm_resource_group.example.location",
						"azurerm_resource_group.example",
					]},
					"name": {"constant_value": "examplekeyvault"},
					"purge_protection_enabled": {"constant_value": true},
					"resource_group_name": {"references": [
						"azurerm_resource_group.example.name",
						"azurerm_resource_group.example",
					]},
					"sku_name": {"constant_value": "premium"},
					"tenant_id": {"references": [
						"data.azurerm_client_config.current.tenant_id",
						"data.azurerm_client_config.current",
					]},
				},
				"schema_version": 2,
			},
			{
				"address": "azurerm_key_vault_access_policy.databricks",
				"mode": "managed",
				"type": "azurerm_key_vault_access_policy",
				"name": "databricks",
				"provider_config_key": "azurerm",
				"expressions": {
					"key_permissions": {"constant_value": [
						"get",
						"unwrapKey",
						"wrapKey",
					]},
					"key_vault_id": {"references": [
						"azurerm_key_vault.example.id",
						"azurerm_key_vault.example",
					]},
					"object_id": {"references": [
						"azurerm_databricks_workspace.valid.storage_account_identity[0].principal_id",
						"azurerm_databricks_workspace.valid.storage_account_identity[0]",
						"azurerm_databricks_workspace.valid.storage_account_identity",
						"azurerm_databricks_workspace.valid",
					]},
					"tenant_id": {"references": [
						"azurerm_databricks_workspace.valid.storage_account_identity[0].tenant_id",
						"azurerm_databricks_workspace.valid.storage_account_identity[0]",
						"azurerm_databricks_workspace.valid.storage_account_identity",
						"azurerm_databricks_workspace.valid",
					]},
				},
				"schema_version": 0,
				"depends_on": ["azurerm_databricks_workspace.valid"],
			},
			{
				"address": "azurerm_key_vault_access_policy.terraform",
				"mode": "managed",
				"type": "azurerm_key_vault_access_policy",
				"name": "terraform",
				"provider_config_key": "azurerm",
				"expressions": {
					"key_permissions": {"constant_value": [
						"get",
						"list",
						"create",
						"decrypt",
						"encrypt",
						"sign",
						"unwrapKey",
						"verify",
						"wrapKey",
						"delete",
						"restore",
						"recover",
						"update",
						"purge",
					]},
					"key_vault_id": {"references": [
						"azurerm_key_vault.example.id",
						"azurerm_key_vault.example",
					]},
					"object_id": {"references": [
						"data.azurerm_client_config.current.object_id",
						"data.azurerm_client_config.current",
					]},
					"tenant_id": {"references": [
						"azurerm_key_vault.example.tenant_id",
						"azurerm_key_vault.example",
					]},
				},
				"schema_version": 0,
			},
			{
				"address": "azurerm_key_vault_key.example",
				"mode": "managed",
				"type": "azurerm_key_vault_key",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"key_opts": {"constant_value": [
						"decrypt",
						"encrypt",
						"sign",
						"unwrapKey",
						"verify",
						"wrapKey",
					]},
					"key_size": {"constant_value": 2048},
					"key_type": {"constant_value": "RSA"},
					"key_vault_id": {"references": [
						"azurerm_key_vault.example.id",
						"azurerm_key_vault.example",
					]},
					"name": {"constant_value": "example-certificate"},
				},
				"schema_version": 0,
				"depends_on": ["azurerm_key_vault_access_policy.terraform"],
			},
			{
				"address": "azurerm_resource_group.example",
				"mode": "managed",
				"type": "azurerm_resource_group",
				"name": "example",
				"provider_config_key": "azurerm",
				"expressions": {
					"location": {"constant_value": "eastus"},
					"name": {"constant_value": "example-resources"},
				},
				"schema_version": 0,
			},
			{
				"address": "data.azurerm_client_config.current",
				"mode": "data",
				"type": "azurerm_client_config",
				"name": "current",
				"provider_config_key": "azurerm",
				"schema_version": 0,
			},
		]},
	},
}
