# Rego test for S3 Bucket Encryption
# Validating rule s3_encryption: Deny S3 Buckets that are not encrypted and/or do not have a valid sse algorithm.
package rules.s3_encryption

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

mock_resources = mock_input.resources

test_s3_encryption {
	resources = mock_input.resources

	count(deny) == 1 with input as resources["aws_s3_bucket.unencrypted"]
	count(deny) == 0 with input as resources["aws_s3_bucket.aes_encrypted"]
	count(deny) == 0 with input as resources["aws_s3_bucket.kms_encrypted"]
}

# Mock input is generated plan for s3_encryption.tf
mock_plan_input = {
	"format_version": "0.1",
	"terraform_version": "0.12.20",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "aws_kms_key.mykey",
			"mode": "managed",
			"type": "aws_kms_key",
			"name": "mykey",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"customer_master_key_spec": "SYMMETRIC_DEFAULT",
				"deletion_window_in_days": 10,
				"description": "This key is used to encrypt bucket objects",
				"enable_key_rotation": false,
				"is_enabled": true,
				"key_usage": "ENCRYPT_DECRYPT",
				"tags": null,
			},
		},
		{
			"address": "aws_s3_bucket.aes_encrypted",
			"mode": "managed",
			"type": "aws_s3_bucket",
			"name": "aes_encrypted",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"acl": "private",
				"bucket": "aes_encrypted",
				"bucket_prefix": null,
				"cors_rule": [],
				"force_destroy": false,
				"grant": [],
				"lifecycle_rule": [],
				"logging": [],
				"object_lock_configuration": [],
				"policy": null,
				"replication_configuration": [],
				"server_side_encryption_configuration": [{"rule": [{"apply_server_side_encryption_by_default": [{"sse_algorithm": "AES256"}]}]}],
				"tags": {
					"Environment": "Dev",
					"Name": "My bucket",
				},
				"website": [],
			},
		},
		{
			"address": "aws_s3_bucket.kms_encrypted",
			"mode": "managed",
			"type": "aws_s3_bucket",
			"name": "kms_encrypted",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"acl": "private",
				"bucket": "kms_encrypted",
				"bucket_prefix": null,
				"cors_rule": [],
				"force_destroy": false,
				"grant": [],
				"lifecycle_rule": [],
				"logging": [],
				"object_lock_configuration": [],
				"policy": null,
				"replication_configuration": [],
				"server_side_encryption_configuration": [{"rule": [{"apply_server_side_encryption_by_default": [{"sse_algorithm": "aws:kms"}]}]}],
				"tags": {
					"Environment": "Dev",
					"Name": "My bucket",
				},
				"website": [],
			},
		},
		{
			"address": "aws_s3_bucket.unencrypted",
			"mode": "managed",
			"type": "aws_s3_bucket",
			"name": "unencrypted",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"acl": "private",
				"bucket": "unencrypted",
				"bucket_prefix": null,
				"cors_rule": [],
				"force_destroy": false,
				"grant": [],
				"lifecycle_rule": [],
				"logging": [],
				"object_lock_configuration": [],
				"policy": null,
				"replication_configuration": [],
				"server_side_encryption_configuration": [{"rule": [{"apply_server_side_encryption_by_default": [{"sse_algorithm": "aws"}]}]}],
				"tags": {
					"Environment": "Dev",
					"Name": "My bucket",
				},
				"website": [],
			},
		},
	]}},
	"resource_changes": [
		{
			"address": "aws_kms_key.mykey",
			"mode": "managed",
			"type": "aws_kms_key",
			"name": "mykey",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"customer_master_key_spec": "SYMMETRIC_DEFAULT",
					"deletion_window_in_days": 10,
					"description": "This key is used to encrypt bucket objects",
					"enable_key_rotation": false,
					"is_enabled": true,
					"key_usage": "ENCRYPT_DECRYPT",
					"tags": null,
				},
				"after_unknown": {
					"arn": true,
					"id": true,
					"key_id": true,
					"policy": true,
				},
			},
		},
		{
			"address": "aws_s3_bucket.aes_encrypted",
			"mode": "managed",
			"type": "aws_s3_bucket",
			"name": "aes_encrypted",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"acl": "private",
					"bucket": "aes_encrypted",
					"bucket_prefix": null,
					"cors_rule": [],
					"force_destroy": false,
					"grant": [],
					"lifecycle_rule": [],
					"logging": [],
					"object_lock_configuration": [],
					"policy": null,
					"replication_configuration": [],
					"server_side_encryption_configuration": [{"rule": [{"apply_server_side_encryption_by_default": [{"sse_algorithm": "AES256"}]}]}],
					"tags": {
						"Environment": "Dev",
						"Name": "My bucket",
					},
					"website": [],
				},
				"after_unknown": {
					"acceleration_status": true,
					"arn": true,
					"bucket_domain_name": true,
					"bucket_regional_domain_name": true,
					"cors_rule": [],
					"grant": [],
					"hosted_zone_id": true,
					"id": true,
					"lifecycle_rule": [],
					"logging": [],
					"object_lock_configuration": [],
					"region": true,
					"replication_configuration": [],
					"request_payer": true,
					"server_side_encryption_configuration": [{"rule": [{"apply_server_side_encryption_by_default": [{"kms_master_key_id": true}]}]}],
					"tags": {},
					"versioning": true,
					"website": [],
					"website_domain": true,
					"website_endpoint": true,
				},
			},
		},
		{
			"address": "aws_s3_bucket.kms_encrypted",
			"mode": "managed",
			"type": "aws_s3_bucket",
			"name": "kms_encrypted",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"acl": "private",
					"bucket": "kms_encrypted",
					"bucket_prefix": null,
					"cors_rule": [],
					"force_destroy": false,
					"grant": [],
					"lifecycle_rule": [],
					"logging": [],
					"object_lock_configuration": [],
					"policy": null,
					"replication_configuration": [],
					"server_side_encryption_configuration": [{"rule": [{"apply_server_side_encryption_by_default": [{"sse_algorithm": "aws:kms"}]}]}],
					"tags": {
						"Environment": "Dev",
						"Name": "My bucket",
					},
					"website": [],
				},
				"after_unknown": {
					"acceleration_status": true,
					"arn": true,
					"bucket_domain_name": true,
					"bucket_regional_domain_name": true,
					"cors_rule": [],
					"grant": [],
					"hosted_zone_id": true,
					"id": true,
					"lifecycle_rule": [],
					"logging": [],
					"object_lock_configuration": [],
					"region": true,
					"replication_configuration": [],
					"request_payer": true,
					"server_side_encryption_configuration": [{"rule": [{"apply_server_side_encryption_by_default": [{"kms_master_key_id": true}]}]}],
					"tags": {},
					"versioning": true,
					"website": [],
					"website_domain": true,
					"website_endpoint": true,
				},
			},
		},
		{
			"address": "aws_s3_bucket.unencrypted",
			"mode": "managed",
			"type": "aws_s3_bucket",
			"name": "unencrypted",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"acl": "private",
					"bucket": "unencrypted",
					"bucket_prefix": null,
					"cors_rule": [],
					"force_destroy": false,
					"grant": [],
					"lifecycle_rule": [],
					"logging": [],
					"object_lock_configuration": [],
					"policy": null,
					"replication_configuration": [],
					"server_side_encryption_configuration": [{"rule": [{"apply_server_side_encryption_by_default": [{"sse_algorithm": "aws"}]}]}],
					"tags": {
						"Environment": "Dev",
						"Name": "My bucket",
					},
					"website": [],
				},
				"after_unknown": {
					"acceleration_status": true,
					"arn": true,
					"bucket_domain_name": true,
					"bucket_regional_domain_name": true,
					"cors_rule": [],
					"grant": [],
					"hosted_zone_id": true,
					"id": true,
					"lifecycle_rule": [],
					"logging": [],
					"object_lock_configuration": [],
					"region": true,
					"replication_configuration": [],
					"request_payer": true,
					"server_side_encryption_configuration": [{"rule": [{"apply_server_side_encryption_by_default": [{"kms_master_key_id": true}]}]}],
					"tags": {},
					"versioning": true,
					"website": [],
					"website_domain": true,
					"website_endpoint": true,
				},
			},
		},
	],
	"configuration": {
		"provider_config": {"aws": {
			"name": "aws",
			"expressions": {
				"profile": {"constant_value": "saml"},
				"region": {"constant_value": "us-east-1"},
				"shared_credentials_file": {"constant_value": "~/.aws/creds"},
			},
		}},
		"root_module": {"resources": [
			{
				"address": "aws_kms_key.mykey",
				"mode": "managed",
				"type": "aws_kms_key",
				"name": "mykey",
				"provider_config_key": "aws",
				"expressions": {
					"deletion_window_in_days": {"constant_value": 10},
					"description": {"constant_value": "This key is used to encrypt bucket objects"},
				},
				"schema_version": 0,
			},
			{
				"address": "aws_s3_bucket.aes_encrypted",
				"mode": "managed",
				"type": "aws_s3_bucket",
				"name": "aes_encrypted",
				"provider_config_key": "aws",
				"expressions": {
					"acl": {"constant_value": "private"},
					"bucket": {"constant_value": "aes_encrypted"},
					"server_side_encryption_configuration": [{"rule": [{"apply_server_side_encryption_by_default": [{
						"kms_master_key_id": {"references": ["aws_kms_key.mykey"]},
						"sse_algorithm": {"constant_value": "AES256"},
					}]}]}],
					"tags": {"constant_value": {
						"Environment": "Dev",
						"Name": "My bucket",
					}},
				},
				"schema_version": 0,
			},
			{
				"address": "aws_s3_bucket.kms_encrypted",
				"mode": "managed",
				"type": "aws_s3_bucket",
				"name": "kms_encrypted",
				"provider_config_key": "aws",
				"expressions": {
					"acl": {"constant_value": "private"},
					"bucket": {"constant_value": "kms_encrypted"},
					"server_side_encryption_configuration": [{"rule": [{"apply_server_side_encryption_by_default": [{
						"kms_master_key_id": {"references": ["aws_kms_key.mykey"]},
						"sse_algorithm": {"constant_value": "aws:kms"},
					}]}]}],
					"tags": {"constant_value": {
						"Environment": "Dev",
						"Name": "My bucket",
					}},
				},
				"schema_version": 0,
			},
			{
				"address": "aws_s3_bucket.unencrypted",
				"mode": "managed",
				"type": "aws_s3_bucket",
				"name": "unencrypted",
				"provider_config_key": "aws",
				"expressions": {
					"acl": {"constant_value": "private"},
					"bucket": {"constant_value": "unencrypted"},
					"server_side_encryption_configuration": [{"rule": [{"apply_server_side_encryption_by_default": [{
						"kms_master_key_id": {"references": ["aws_kms_key.mykey"]},
						"sse_algorithm": {"constant_value": "aws"},
					}]}]}],
					"tags": {"constant_value": {
						"Environment": "Dev",
						"Name": "My bucket",
					}},
				},
				"schema_version": 0,
			},
		]},
	},
}
