# Rego Test for redshfit cluster encryption at rest
package rules.redshift_cluster_encrypted

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

mock_resources = mock_input.resources

test_redshift_cluster_encrypted {
	resources = mock_input.resources

	count(deny) == 0 with input as resources["aws_redshift_cluster.valid"]
	count(deny) == 1 with input as resources["aws_redshift_cluster.invalid"]
}

# Mock input in generated from redshift_encrypted.tf
mock_plan_input = {
	"configuration": {
		"provider_config": {"aws": {
			"expressions": {
				"profile": {"constant_value": "saml"},
				"region": {"constant_value": "us-east-1"},
				"shared_credentials_file": {"constant_value": "~/.aws/creds"},
			},
			"name": "aws",
		}},
		"root_module": {"resources": [
			{
				"address": "aws_redshift_cluster.invalid",
				"expressions": {
					"cluster_identifier": {"constant_value": "tf-redshift-cluster"},
					"cluster_type": {"constant_value": "single-node"},
					"database_name": {"constant_value": "mydb"},
					"master_password": {"constant_value": "Mustbe8characters"},
					"master_username": {"constant_value": "foo"},
					"node_type": {"constant_value": "dc1.large"},
				},
				"mode": "managed",
				"name": "invalid",
				"provider_config_key": "aws",
				"schema_version": 0,
				"type": "aws_redshift_cluster",
			},
			{
				"address": "aws_redshift_cluster.valid",
				"expressions": {
					"cluster_identifier": {"constant_value": "tf-redshift-cluster-valid"},
					"cluster_type": {"constant_value": "single-node"},
					"database_name": {"constant_value": "mynewdb"},
					"encrypted": {"constant_value": true},
					"master_password": {"constant_value": "Mustbe8characters"},
					"master_username": {"constant_value": "foo"},
					"node_type": {"constant_value": "dc1.large"},
				},
				"mode": "managed",
				"name": "valid",
				"provider_config_key": "aws",
				"schema_version": 0,
				"type": "aws_redshift_cluster",
			},
		]},
	},
	"format_version": "0.1",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "aws_redshift_cluster.invalid",
			"mode": "managed",
			"name": "invalid",
			"provider_name": "aws",
			"schema_version": 0,
			"type": "aws_redshift_cluster",
			"values": {
				"allow_version_upgrade": true,
				"automated_snapshot_retention_period": 1,
				"cluster_identifier": "tf-redshift-cluster",
				"cluster_type": "single-node",
				"cluster_version": "1.0",
				"database_name": "mydb",
				"elastic_ip": null,
				"encrypted": false,
				"final_snapshot_identifier": null,
				"logging": [],
				"master_password": "Mustbe8characters",
				"master_username": "foo",
				"node_type": "dc1.large",
				"number_of_nodes": 1,
				"owner_account": null,
				"port": 5439,
				"publicly_accessible": true,
				"skip_final_snapshot": false,
				"snapshot_cluster_identifier": null,
				"snapshot_copy": [],
				"snapshot_identifier": null,
				"tags": null,
				"timeouts": null,
			},
		},
		{
			"address": "aws_redshift_cluster.valid",
			"mode": "managed",
			"name": "valid",
			"provider_name": "aws",
			"schema_version": 0,
			"type": "aws_redshift_cluster",
			"values": {
				"allow_version_upgrade": true,
				"automated_snapshot_retention_period": 1,
				"cluster_identifier": "tf-redshift-cluster-valid",
				"cluster_type": "single-node",
				"cluster_version": "1.0",
				"database_name": "mynewdb",
				"elastic_ip": null,
				"encrypted": true,
				"final_snapshot_identifier": null,
				"logging": [],
				"master_password": "Mustbe8characters",
				"master_username": "foo",
				"node_type": "dc1.large",
				"number_of_nodes": 1,
				"owner_account": null,
				"port": 5439,
				"publicly_accessible": true,
				"skip_final_snapshot": false,
				"snapshot_cluster_identifier": null,
				"snapshot_copy": [],
				"snapshot_identifier": null,
				"tags": null,
				"timeouts": null,
			},
		},
	]}},
	"resource_changes": [
		{
			"address": "aws_redshift_cluster.invalid",
			"change": {
				"actions": ["create"],
				"after": {
					"allow_version_upgrade": true,
					"automated_snapshot_retention_period": 1,
					"cluster_identifier": "tf-redshift-cluster",
					"cluster_type": "single-node",
					"cluster_version": "1.0",
					"database_name": "mydb",
					"elastic_ip": null,
					"encrypted": false,
					"final_snapshot_identifier": null,
					"logging": [],
					"master_password": "Mustbe8characters",
					"master_username": "foo",
					"node_type": "dc1.large",
					"number_of_nodes": 1,
					"owner_account": null,
					"port": 5439,
					"publicly_accessible": true,
					"skip_final_snapshot": false,
					"snapshot_cluster_identifier": null,
					"snapshot_copy": [],
					"snapshot_identifier": null,
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {
					"arn": true,
					"availability_zone": true,
					"bucket_name": true,
					"cluster_parameter_group_name": true,
					"cluster_public_key": true,
					"cluster_revision_number": true,
					"cluster_security_groups": true,
					"cluster_subnet_group_name": true,
					"dns_name": true,
					"enable_logging": true,
					"endpoint": true,
					"enhanced_vpc_routing": true,
					"iam_roles": true,
					"id": true,
					"kms_key_id": true,
					"logging": [],
					"preferred_maintenance_window": true,
					"s3_key_prefix": true,
					"snapshot_copy": [],
					"vpc_security_group_ids": true,
				},
				"before": null,
			},
			"mode": "managed",
			"name": "invalid",
			"provider_name": "aws",
			"type": "aws_redshift_cluster",
		},
		{
			"address": "aws_redshift_cluster.valid",
			"change": {
				"actions": ["create"],
				"after": {
					"allow_version_upgrade": true,
					"automated_snapshot_retention_period": 1,
					"cluster_identifier": "tf-redshift-cluster-valid",
					"cluster_type": "single-node",
					"cluster_version": "1.0",
					"database_name": "mynewdb",
					"elastic_ip": null,
					"encrypted": true,
					"final_snapshot_identifier": null,
					"logging": [],
					"master_password": "Mustbe8characters",
					"master_username": "foo",
					"node_type": "dc1.large",
					"number_of_nodes": 1,
					"owner_account": null,
					"port": 5439,
					"publicly_accessible": true,
					"skip_final_snapshot": false,
					"snapshot_cluster_identifier": null,
					"snapshot_copy": [],
					"snapshot_identifier": null,
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {
					"arn": true,
					"availability_zone": true,
					"bucket_name": true,
					"cluster_parameter_group_name": true,
					"cluster_public_key": true,
					"cluster_revision_number": true,
					"cluster_security_groups": true,
					"cluster_subnet_group_name": true,
					"dns_name": true,
					"enable_logging": true,
					"endpoint": true,
					"enhanced_vpc_routing": true,
					"iam_roles": true,
					"id": true,
					"kms_key_id": true,
					"logging": [],
					"preferred_maintenance_window": true,
					"s3_key_prefix": true,
					"snapshot_copy": [],
					"vpc_security_group_ids": true,
				},
				"before": null,
			},
			"mode": "managed",
			"name": "valid",
			"provider_name": "aws",
			"type": "aws_redshift_cluster",
		},
	],
	"terraform_version": "0.12.19",
}
