# Rego test file for redshift logging 
# Validating rule ensures that redshift clusters have logging enabled
package rules.redshift_logging

import data.fugue.resource_view.resource_view_input

mock_input = ret {
	ret = resource_view_input with input as mock_plan_input
}

test_redshift_logging {
	pol := policy with input as mock_input
	resources := {p.id: p.valid | pol[p]}

	resources["aws_redshift_cluster.valid"] == true
	resources["aws_redshift_cluster.invalid"] == false
}

# Mock input is generated from redshift_logging.tf 
# Valid when redshift logging is enabled
mock_plan_input = {
	"format_version": "0.1",
	"terraform_version": "0.12.28",
	"planned_values": {"root_module": {"resources": [
		{
			"address": "aws_redshift_cluster.invalid",
			"mode": "managed",
			"type": "aws_redshift_cluster",
			"name": "invalid",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"allow_version_upgrade": true,
				"automated_snapshot_retention_period": 1,
				"cluster_identifier": "tf-redshift-cluster-invalid",
				"cluster_type": "single-node",
				"cluster_version": "1.0",
				"database_name": "mydb",
				"elastic_ip": null,
				"encrypted": false,
				"final_snapshot_identifier": null,
				"logging": [],
				"master_password": "Mustbe8characters",
				"master_username": "foo",
				"node_type": "dc1.large",
				"number_of_nodes": 1,
				"owner_account": null,
				"port": 5439,
				"publicly_accessible": true,
				"skip_final_snapshot": false,
				"snapshot_cluster_identifier": null,
				"snapshot_copy": [],
				"snapshot_identifier": null,
				"tags": null,
				"timeouts": null,
			},
		},
		{
			"address": "aws_redshift_cluster.valid",
			"mode": "managed",
			"type": "aws_redshift_cluster",
			"name": "valid",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"allow_version_upgrade": true,
				"automated_snapshot_retention_period": 1,
				"cluster_identifier": "tf-redshift-cluster-valid",
				"cluster_type": "single-node",
				"cluster_version": "1.0",
				"database_name": "mydb",
				"elastic_ip": null,
				"encrypted": false,
				"final_snapshot_identifier": null,
				"logging": [{
					"bucket_name": "aws_s3_bucket.b",
					"enable": true,
				}],
				"master_password": "Mustbe8characters",
				"master_username": "foo",
				"node_type": "dc1.large",
				"number_of_nodes": 1,
				"owner_account": null,
				"port": 5439,
				"publicly_accessible": true,
				"skip_final_snapshot": false,
				"snapshot_cluster_identifier": null,
				"snapshot_copy": [],
				"snapshot_identifier": null,
				"tags": null,
				"timeouts": null,
			},
		},
		{
			"address": "aws_s3_bucket.b",
			"mode": "managed",
			"type": "aws_s3_bucket",
			"name": "b",
			"provider_name": "aws",
			"schema_version": 0,
			"values": {
				"acl": "private",
				"bucket": "my-tf-test-bucket",
				"bucket_prefix": null,
				"cors_rule": [],
				"force_destroy": false,
				"grant": [],
				"lifecycle_rule": [],
				"logging": [],
				"object_lock_configuration": [],
				"policy": null,
				"replication_configuration": [],
				"server_side_encryption_configuration": [],
				"tags": {
					"Environment": "Dev",
					"Name": "My bucket",
				},
				"website": [],
			},
		},
	]}},
	"resource_changes": [
		{
			"address": "aws_redshift_cluster.invalid",
			"mode": "managed",
			"type": "aws_redshift_cluster",
			"name": "invalid",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"allow_version_upgrade": true,
					"automated_snapshot_retention_period": 1,
					"cluster_identifier": "tf-redshift-cluster-invalid",
					"cluster_type": "single-node",
					"cluster_version": "1.0",
					"database_name": "mydb",
					"elastic_ip": null,
					"encrypted": false,
					"final_snapshot_identifier": null,
					"logging": [],
					"master_password": "Mustbe8characters",
					"master_username": "foo",
					"node_type": "dc1.large",
					"number_of_nodes": 1,
					"owner_account": null,
					"port": 5439,
					"publicly_accessible": true,
					"skip_final_snapshot": false,
					"snapshot_cluster_identifier": null,
					"snapshot_copy": [],
					"snapshot_identifier": null,
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {
					"arn": true,
					"availability_zone": true,
					"cluster_parameter_group_name": true,
					"cluster_public_key": true,
					"cluster_revision_number": true,
					"cluster_security_groups": true,
					"cluster_subnet_group_name": true,
					"dns_name": true,
					"endpoint": true,
					"enhanced_vpc_routing": true,
					"iam_roles": true,
					"id": true,
					"kms_key_id": true,
					"logging": [],
					"preferred_maintenance_window": true,
					"snapshot_copy": [],
					"vpc_security_group_ids": true,
				},
			},
		},
		{
			"address": "aws_redshift_cluster.valid",
			"mode": "managed",
			"type": "aws_redshift_cluster",
			"name": "valid",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"allow_version_upgrade": true,
					"automated_snapshot_retention_period": 1,
					"cluster_identifier": "tf-redshift-cluster-valid",
					"cluster_type": "single-node",
					"cluster_version": "1.0",
					"database_name": "mydb",
					"elastic_ip": null,
					"encrypted": false,
					"final_snapshot_identifier": null,
					"logging": [{
						"bucket_name": "aws_s3_bucket.b",
						"enable": true,
					}],
					"master_password": "Mustbe8characters",
					"master_username": "foo",
					"node_type": "dc1.large",
					"number_of_nodes": 1,
					"owner_account": null,
					"port": 5439,
					"publicly_accessible": true,
					"skip_final_snapshot": false,
					"snapshot_cluster_identifier": null,
					"snapshot_copy": [],
					"snapshot_identifier": null,
					"tags": null,
					"timeouts": null,
				},
				"after_unknown": {
					"arn": true,
					"availability_zone": true,
					"cluster_parameter_group_name": true,
					"cluster_public_key": true,
					"cluster_revision_number": true,
					"cluster_security_groups": true,
					"cluster_subnet_group_name": true,
					"dns_name": true,
					"endpoint": true,
					"enhanced_vpc_routing": true,
					"iam_roles": true,
					"id": true,
					"kms_key_id": true,
					"logging": [{"s3_key_prefix": true}],
					"preferred_maintenance_window": true,
					"snapshot_copy": [],
					"vpc_security_group_ids": true,
				},
			},
		},
		{
			"address": "aws_s3_bucket.b",
			"mode": "managed",
			"type": "aws_s3_bucket",
			"name": "b",
			"provider_name": "aws",
			"change": {
				"actions": ["create"],
				"before": null,
				"after": {
					"acl": "private",
					"bucket": "my-tf-test-bucket",
					"bucket_prefix": null,
					"cors_rule": [],
					"force_destroy": false,
					"grant": [],
					"lifecycle_rule": [],
					"logging": [],
					"object_lock_configuration": [],
					"policy": null,
					"replication_configuration": [],
					"server_side_encryption_configuration": [],
					"tags": {
						"Environment": "Dev",
						"Name": "My bucket",
					},
					"website": [],
				},
				"after_unknown": {
					"acceleration_status": true,
					"arn": true,
					"bucket_domain_name": true,
					"bucket_regional_domain_name": true,
					"cors_rule": [],
					"grant": [],
					"hosted_zone_id": true,
					"id": true,
					"lifecycle_rule": [],
					"logging": [],
					"object_lock_configuration": [],
					"region": true,
					"replication_configuration": [],
					"request_payer": true,
					"server_side_encryption_configuration": [],
					"tags": {},
					"versioning": true,
					"website": [],
					"website_domain": true,
					"website_endpoint": true,
				},
			},
		},
	],
	"configuration": {
		"provider_config": {"aws": {
			"name": "aws",
			"expressions": {
				"profile": {"constant_value": "saml"},
				"region": {"constant_value": "us-east-1"},
				"shared_credentials_file": {"constant_value": "~/.aws/creds"},
			},
		}},
		"root_module": {"resources": [
			{
				"address": "aws_redshift_cluster.invalid",
				"mode": "managed",
				"type": "aws_redshift_cluster",
				"name": "invalid",
				"provider_config_key": "aws",
				"expressions": {
					"cluster_identifier": {"constant_value": "tf-redshift-cluster-invalid"},
					"cluster_type": {"constant_value": "single-node"},
					"database_name": {"constant_value": "mydb"},
					"master_password": {"constant_value": "Mustbe8characters"},
					"master_username": {"constant_value": "foo"},
					"node_type": {"constant_value": "dc1.large"},
				},
				"schema_version": 0,
			},
			{
				"address": "aws_redshift_cluster.valid",
				"mode": "managed",
				"type": "aws_redshift_cluster",
				"name": "valid",
				"provider_config_key": "aws",
				"expressions": {
					"cluster_identifier": {"constant_value": "tf-redshift-cluster-valid"},
					"cluster_type": {"constant_value": "single-node"},
					"database_name": {"constant_value": "mydb"},
					"logging": [{
						"bucket_name": {"constant_value": "aws_s3_bucket.b"},
						"enable": {"constant_value": true},
					}],
					"master_password": {"constant_value": "Mustbe8characters"},
					"master_username": {"constant_value": "foo"},
					"node_type": {"constant_value": "dc1.large"},
				},
				"schema_version": 0,
			},
			{
				"address": "aws_s3_bucket.b",
				"mode": "managed",
				"type": "aws_s3_bucket",
				"name": "b",
				"provider_config_key": "aws",
				"expressions": {
					"acl": {"constant_value": "private"},
					"bucket": {"constant_value": "my-tf-test-bucket"},
					"tags": {"constant_value": {
						"Environment": "Dev",
						"Name": "My bucket",
					}},
				},
				"schema_version": 0,
			},
		]},
	},
}
