on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Confectionery Integration Checks
    steps:
    - uses: actions/checkout@v2
    - uses: open-policy-agent/setup-opa@v1
    - run: ./scripts/check-naming.sh
    - run: ./scripts/opa-format.sh
    - run: opa test rules test-files
